### ISSUE TITLE
Error messages being displayed on console for news

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1001]
**Describe the bug**
Several console errors being displayed for news
<img width="737" alt="Skjermbilde 2022-04-11 kl  09 53 29" src="https://user-images.githubusercontent.com/1836295/162714548-81b1070e-4a24-4912-a71a-6e0fc2e78de0.png">

**Comment by SvSven** [comment]
I'm not able to reproduce this, not in the newsroom nor a news article - neither archived nor Sanity news.

However if I were to take a wild guess then I think the problem is it's trying to render a field that has no value; will double check the code and make sure we check for values before rendering.

**Comment by SvSven** [comment]
Added some additional guards to check if the block content arrays (content and ingress) have a length greater than 0.
Not sure if that was what caused these errors, but it never hurts.
