### ISSUE TITLE
Text snippets in search not showing Norwegian translation in /no/

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1013]
As of writing, the labels in search when on the Norwegian website are showing the English version, despite translations being available in the studio.

https://energyvision.app.radix.equinor.com/no/search?query=equinor

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/505a609a-77d0-4b31-8f43-7761724ce3fe)

**Comment by wenche** [comment]
This doesn't happen with build + start locally. The language should be attached during static build, so it's a litte bit hard to tell the difference here. However, the /search page doesn't have revalidate so I'm adding that to the code since we need to revalidate in between builds if the menu or footer data updates. This might mask the original issue though.

**Comment by wenche** [comment]
I'm not sure how much time we should spend on this. With the revalidate time added, it has the correct Norwegian translations for the search overlay. What do you say Sven, do yo think it's good enough?
