### ISSUE TITLE
Add ErrorBoundary component

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1032]
Crashing the application when there's a client side error is not optimal. Look into adding an ErrorBoundary component, probably something like the [suggested approach from the Next.js docs](https://nextjs.org/docs/advanced-features/error-handling#handling-client-errors) will cover our needs.

**Comment by SvSven** [comment]
I have added an ErrorBoundary component to the `_app.tsx` that should catch and handle fatal client errors, using the `react-error-boundary` wrapper package: https://github.com/bvaughn/react-error-boundary

See: https://github.com/equinor/energyvision/commit/e3c2c110acece33db38fadb474f072296db45e7f

It has a basic but nice design for now: 
![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/ca270628-595a-4a6f-b35a-cbde1e38bcc5)

In order to test this, you will need to do some local changes (don't commit those):

import `useState` in `_app.tsx`

Add the following to `MyApp`:

```ts
const [explode, setExplode] = useState(false)

function Bomb() {
  throw new Error('💥 CABOOM 💥')
}
```

then add the following to the render function:

```ts
{explode ? <Bomb /> : ''}
<button onClick={() => setExplode(true)}>explode</button>
```

and add this reset handler to the `ErrorBoundary` component: 

```ts
onReset={() => setExplode(false)}
```
