### ISSUE TITLE
Update jest to v28

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1040]
Jest v28 has some breaking changes we have to look at: https://github.com/facebook/jest/releases/tag/v28.0.0

Updating it without changes unfortunately breaks our setup

**Comment by wenche** [comment]
I think I finally made this. The root cause for the undefined errors was this line in the jest.config.js file:
`moduleDirectories: ['node_modules', './'],`
 I also removed the babel transpiiler as it is no longer needed, and used the [new next/jest feature ](https://nextjs.org/docs/advanced-features/compiler#jest). @SvSven  ?

**Comment by SvSven** [comment]
Looks good to me 👍
Such a small but impactful problem 🙈
