### ISSUE TITLE
Do not display default locale in sitemap

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1078]

**Comment by fernandolucchesi** [comment]
@SvSven can you check this one?

**Comment by SvSven** [comment]
Not 100% sure what the problem here was, but I'm guessing it's that `/en/` was showing in the sitemap URLs for the English language one?

If so then it looks to be solved when I compare dev to production:
- https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/sitemap.xml?lang=en
- https://www.equinor.com/sitemap.xml?lang=en
