### ISSUE TITLE
Anchor on promo tiles not working

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1103]
Acceptance criteria:
- [ ] Update documentation in Runbook (add new anchor component too)

**Comment by meols** [comment]
The anchor link on promo tiles isn't working.
Tested on this page: https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/mette-test-1

**Comment by wenche** [comment]
LGTM :thumbsup:

@meols  You can retest in your page :)

**Comment by jorgol** [comment]
Still doesn't seem to work? 

https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/mette-test-1#anchor-test

**Comment by SvSven** [comment]
Seems like the issue is not so much with the promo tile link, but with the anchor references that is being linked to.
The `anchor reference` in the link needs to match the `anchor` of a component, and on that particular page there are no components that have the anchor `anchor-test` or `2` - so there is nothing to link to.

We recently changed the way we do anchors, it's now a dedicated component that you can add _above_ any component you want to link to:

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/34326d1f-6cc3-4a71-a835-afb691d74199)

I created one of those with `anchor-test` and now the link in the promo tile works correctly.

**Comment by jorgol** [comment]
Yes, I mixed up the anchor reference and the actual anchor.

So both with regard to that and the fact that we have a new anchor link component means this story can be approved/closed. :)
