### ISSUE TITLE
Integrate Fotoware with Sanity

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1116]
Brandmaster DAM will be replaced by Fotoware on 30th June. 
#592 and https://github.com/equinor/energyvision-internal/discussions/49 for more details.

Acceptance criteria:
- [ ] Update documentation in Runbook

**Comment by SvSven** [comment]
@fernandolucchesi @padms 

This should now be ready for technical review. You can find all the code for it here: https://github.com/equinor/energyvision/tree/main/studio/plugins/asset-source-fotoware

Took the liberty of adding a README explaining the workflow as well, since this is a little bit more complex than the BrandMaster integration we have.

The Azure Functions used for authentication and base64 converting are in a separate private repository.

**Comment by fernandolucchesi** [comment]
Works and code looks good ✅  

- just a reminder to update runbook before closing this issue

**Comment by SvSven** [comment]
Some feedback from editorial team:

For Fotoware UI:
- Can we create crop presets like 16:9 (to not have to write pixel size every time)?
- Can the select button be called OK or Select instead of Publish? (a bit strange to see the blue Sanity publish button behind the blue Fotoware Publish button)
- Can we avoid seeing the Smart folders and have thumbnails in the whole window?
- The search in the select widget is weird, it doesn't search inside an archive but the whole of Fotoware. Not the same as in the web application of Fotoware either.

For integration:
- Can we get the title and description from Fotoware into Sanity (on the asset document like Brandmaster)
- Is it possible to auto-fill fields when selecting image

**Comment by SvSven** [comment]
Fotoware does not broadcast the widget events to the `window.opener` parent, only to the `window.parent` which means it only works inside an iframe - as such I have done some (ugly) style overriding on the dialog to make the modal full-screen, which should help a good deal already.

Additionally I've made sure to pass the asset's title and description onto the Sanity asset document, similar to how we do this for Brandmaster.

Auto-filling fields such as the alt attribute inside the studio is a bit of a bigger issue and not one very easily solved. It's definitely something to look into though because it could be useful for other things as well.
I had a look at this plugin to see if we can use that for it: https://github.com/wildseansy/sanity-plugin-computed-field
But that does not have the `document.context` scope, which we would need to get the ID of the image to run a query with.

For reference though, this is how we can get the asset document with GROQ: 

```
*[_type == "sanity.imageAsset" && _id == $id]
```

where `$id` is the `_id` or `_ref` of the asset.

---

As for the other points: those are questions we can pass along to Fotoware, but I don't think we can customize the UI for the widgets unfortunately. It does present a challenge in that editors _can_ select non-image assets (like videos), while those are not supported inside Sanity (since we are using an image field).

**Comment by fernandolucchesi** [comment]
Hi @meols @nicholas-haggerty @jorgol, can you please review this one on https://studio-global-test-equinor-web-sites-test.c2.radix.equinor.com/

**Comment by meols** [comment]
Thanks @fernandolucchesi - this is approved (but we need to continue a dialogue with Fotoware regarding some comments from the editorial team)

**Comment by fernandolucchesi** [comment]
@SvSven is runbook updated?

**Comment by SvSven** [comment]
Runbook has been updated ✅
I'll create a diagram to better show how all the things are connected as well.
