### ISSUE TITLE
Secret project failing to duplicate documents

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1129]
<img width="839" alt="image" src="https://user-images.githubusercontent.com/23337266/172320022-a37cd095-9195-4e36-8218-6e04b32f7415.png">

**Comment by fernandolucchesi** [comment]
Hi @meols, can you confirm this is working as intended?

**Comment by meols** [comment]
I tested this news https://equinor-restricted.sanity.studio/secret/desk/news;202c3de7-d79f-4233-9d14-faa87829598e%2Ctype%3Dnews 
I published the Norwegian first and got an error when publishing the English one. Then I pressed Reset Cross Dataset Token, but since the Publish button was grey I checked the Current version status, and saw that it actually got published, even if I got an error message.
