### ISSUE TITLE
Events grid should adapt to number of items

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1137]
![image.png](https://images.zenhubusercontent.com/619cb66996a338308e2dd0b8/13deb39d-5b41-4c8c-ae7c-1839a777611c)

**Comment by wenche** [comment]
This was how it was made back in the days, because we didn't want the event card to be wider then a certain width and it didn't look good if you had only one or more events. Be careful :)

A better approach might be to look at the grids for local news, promotions, people +++ at a more high level as we kind of solve the same/very related problem in a number of different ways.

**Comment by NickHaggerty1** [comment]
@meols Relating to this maybe. needs to be looked at, at some point!

**Comment by fernandolucchesi** [comment]
Relates to your feedback @meols #1063

**Comment by fernandolucchesi** [comment]
@millianapia you did work on something related to this right? is this fixed?
