### ISSUE TITLE
Do not make it possible to select non-SVG images in the Text with icon component

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1149]
This is for making things more understandable for the publisers.

### Background
We do have an `accept` for the svg filetype only if you upload a new image to the Text with icon component. However, this limitation is not reflected when you select an existing image. 

### To investigate
Can we add a validation to the image field that will only allow for file types of SVG? We don't know if this is possible or not in Sanity

Related to https://github.com/sanity-io/sanity/issues/1519

**Comment by fernandolucchesi** [comment]
@padms, can you link the commit to the changes?

**Comment by padms** [comment]
Pushed it with a wrong commit message https://github.com/equinor/energyvision/commit/a32d6a858053a3b448ec1fb336f9807ce2582aa3

**Comment by fernandolucchesi** [comment]
Looks good but you forgot a type check.. left a comment :)

**Comment by padms** [comment]
@meols The icon field in Icon and text component does not allow non svg files now.

**Comment by meols** [comment]
@padms @fernandolucchesi  - two questions to this:
1. Is it possible to not be able to choose "All files" when uploading a file. Editors now can change to "All files" and see many file types and choose e.g. a .png or .jpg, but nothing happens after that.
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/8579c4fc-ac1c-48bb-bdd6-fbe20dbe7eed)
2. Is it possible to link directly to the "Icons and illustrations" (instead of the "Mediabank for photo"), now that we don't use Brandmaster for images anymore?
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/c1a99c51-2fc3-444f-8609-b49b3249c06a)

**Comment by padms** [comment]
https://equinor.slack.com/archives/C01A4BGNRMJ/p1662996122223379

**Comment by meols** [comment]
@padms @fernandolucchesi - should this card be moved to the _Dependent on others_ lane for now?
