### ISSUE TITLE
Horizontal tag component

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1268]
NEW tag list displayed horizontally, including magazine search to the right. This should show the 5 (or fewer) "promoted tags selected by editors ( https://github.com/equinor/energyvision/issues/1226 ), This tag list should also be implemented to the magazine template page.

For reference: #1251 https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=5977%3A90557

**Comment by padms** [comment]
@NickHaggerty1 @meols Quick question here. The horizontal bar in the magazine template page should display the tags that are added to that page. Is this correct? or should we have separate tag list to display? ![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/cdf20008-e743-405b-addb-b851f63b606c)

**Comment by NickHaggerty1** [comment]
@padms @meols @fernandolucchesi   It could be done separately like you have with a NEW display on each template. However this would mean the horizontal bar on each article would be editable. Correct? This is not really what we want. We were thinking more that in the MAGAZINE TAGS (where we create the tags) there would be a hierarchy option there instead (tick on /off to display in magazine bar for example) with a maximum display of 5. So Editor could choose/tick 5 from the list of magazine tags and this would display on ALL mag templates bars. If editor decides to change one, then has to deselect one in order to add one. By editing here instead, the editor wouldnt need to go through every template to change. And we ensure consistency by not having option to change at an article level... Make sense? Doable?

**Comment by NickHaggerty1** [comment]
Note we would still like the option to add other magazine tags to an article as you have already set up, so this doesn't change.

**Comment by padms** [comment]
@NickHaggerty1  ![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/da6fa98a-4e13-4d60-a575-abd7a0095abf)  
Created a menu item for this, which will be applied to all magazine pages.

**Comment by NickHaggerty1** [comment]
@padms This looks excellent I think @meols agree?

**Comment by nilsml** [comment]
Can you review this @fernandolucchesi?

**Comment by fernandolucchesi** [comment]
@padms,

1. the border color you used is too dark compared to the ones in the design. In the design it is used #D3D7DA, we need to find a color var that is close to that.
2. when navigating from a magazine page to a tag that has no results (like innovation), the ALL tag is the one highlighted: 
<img width="878" alt="image" src="https://user-images.githubusercontent.com/23337266/192910370-61d74b9d-819a-4a72-b658-01581ea9dfb1.png">
3. When navigating back and forth on the browser / clicking on tags, an error is displayed on the console: 
<img width="604" alt="image" src="https://user-images.githubusercontent.com/23337266/192910555-fd468a1d-87c0-4e08-b6b5-24779d65a8c0.png">

**Comment by fernandolucchesi** [comment]
left comments in your commits. once you fix those i'll do a 2nd round of review

**Comment by padms** [comment]
1,2 and 3 fixed.

**Comment by fernandolucchesi** [comment]
Hi @padms, left a suggestion.

Otherwise, for #1, the color should be (--grey-30). I know the figma file says slate blue but if you look at the hex code it is actually from the grey-30.

Also when inside a magazine the "ALL" is always selected. I think the correct would be no tags selected, OR the tags belonging to the magazine itself selected.

**Comment by padms** [comment]
@fernandolucchesi  Please check now

**Comment by fernandolucchesi** [comment]
Looks good! ✅

**Comment by padms** [comment]
@meols @NickHaggerty1  Magazine tag bar is ready to be reviewed now. This component can be updated in the magazine index page, and will be reflected in all the magazine pages.

**Comment by NickHaggerty1** [comment]
Approved. Thanks
