### ISSUE TITLE
Create disaster recovery epic with small issues

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1282]
energyvision-internal#32

**Comment by SvSven** [comment]
## Things to keep in mind
- Kan vi simulere at Sanity er nede? Hvem kontakter vi og hvordan?
- How can we know that Sanity's backup restoration works? Can we do simulations with them?
- Who to contact in Sanity? Should be in our contract.
- What happens if Sanity is down for a short period? Will pages be cashed? For how long?
- What kind of response time is to be expected by Sanity and internally?
- How is equinor.com prioritized if "shit hits the fan"?
- Emergency plan - should we have one
- Should we add a layer in Azure for handling situations when our cluster is down? More info: https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview

**Comment by fernandolucchesi** [comment]
Backups: https://www.sanity.io/plugins/backups

**Comment by nilsml** [comment]
Epic #1099 updated with new issues. Next step is to go through the task list with decision makers.

**Comment by nilsml** [comment]
Closing this in favour of https://github.com/equinor/energyvision-internal/issues/32
