### ISSUE TITLE
Investigate and list where we should add structured data

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1283]
Which categories are relevant and how can they be implemented on Equinor pages (templates / pages)?

Make a list of places where structured data can be added and add to #1270 description

**Comment by padms** [comment]
Added findings in #1270 description

**Comment by SvSven** [comment]
I think that's a good start. Not sure if adding it for a people promotion causes any issues if there are multiple people promotions, but it's worth looking into. It's a shame they chose to have all the CVs as an accordion on a single page; we could otherwise add structured data on a per-person basis if everyone important enough had their own URL.

We should check with the SEO agency if they have a recommendation on which format to use. Interestingly enough I can't view the JSON LD website; it's blocked as "Malicious Sources" on Equinor devices 😅

**Comment by fernandolucchesi** [comment]
Closing this, created #1270
