### ISSUE TITLE
Upgrade Next Image components to newest

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#1364]
When we upgraded to next 13, we put the next image component import as `'next/legacy/image'` to not create any breaking changes. Each mention of the image component should to be upgraded to next/image so we can use the newest image functionalities in next 13

**Comment by millianapia** [comment]
@fernandolucchesi I refactored most of the components as i was not too happy with how objectFit was used, and generally some refactor of featureflags and adding new ones. I also removed the unopmitized prop. SO, As layout and object fit prop is not used anymore as a prop in the new component, i rewrote the default component to have responsive layout prop with styling, and adding objectfit as a style prop directly on the components where the image component itself is used. 

so - when we are going to start using the new next image component, we will have to remove and refactor all instances of layout prop, and use a check if fill is present or not; just a cleanup, not too big of a job:)

**Comment by fernandolucchesi** [comment]
Hi @millianapia, looks like everything works as it should! So nice job!  However, I also think that we could use this issue as an opportunity to refactor the whole Image.tsx file, since the logic there is very old and looks like Frankenstein. 

From what I can understand of our code, our component only uses two layout options: fill and responsive. I would suggest we create a new Image wrapper for the Next 13 images, and make sure we are using only what is really needed for each layout.

For example, in the `NewImg` component you created, the prop "sizes" is being used when the layout is 'fill'. From [the docs](https://github.com/bundlesandbatches/next-sanity-image), looks like we can omit that, but hard to make sure nothing else will break.

My suggestion is to have a component that takes the layout as a prop, and conditionally checks if other props are required by typescript, something like:

```
type ImageType = ...
type = {
    layout: 'fill'
} & ImageType | {
   layout: 'responsive',
   sizes: string
 } & ImageType etcs 
```

It would also be nice to have a switch statement for the returning of the images to make it more readable, and comments explaining the differences between each layout, as they provide in the docs:
```
switch (layout) { 
   ...
}
```

Annnd, looks like your prettier has stopped working 😅 

Let me know what do you think

**Comment by millianapia** [comment]
nice refactoring suggestion! Had something similar in mind, wanted to introduce them after we had "accepted" the new changes, but i can fix the refactoring now:)

**Comment by millianapia** [comment]
as the layout prop is removed in the new image component, i would rather propose this refactoring:
```

const responsive = { 
    width: '100%',
    height: 'auto',
  }

  return (
    <NewImg
      {...rest}
      {...imageProps}
      alt={altTag}
      sizes={sizes}
      fill={fill}
      style={layout=="responsive" ? responsive : {} }
      role={image?.isDecorative ? 'presentation' : undefined}
      placeholder={placeholder}
      unoptimized={unoptimized}
    />
  )
```

as responsive is our default layout anyway, and fill is optional, as well as sizes depending on how it is used in different places

**Comment by millianapia** [comment]
or if we remove the layout completely, and use this instead:

`      style={!fill ? responsive : {} }
`

as, if the fill is present, the layout is fill, but if not, the layout is responsive

**Comment by SvSven** [comment]
I recall we had quite some issues with the layout stuff when this was initially created - but that was several versions of both Next and the `next-sanity-image` plugin ago.

**Comment by millianapia** [comment]
like the new changes, but might be biased due to the amount of hours i have looked on this component

**Comment by fernandolucchesi** [comment]
@meols there is no very good way to review this since it is very technical and the end result should be the same as before, so can you please check that all images still work on dev? 😅

**Comment by meols** [comment]
:rofl: @fernandolucchesi The ones I've seen are working :rofl:

**Comment by meols** [comment]
:rofl: @fernandolucchesi The ones I've seen are working :rofl:

**Comment by fernandolucchesi** [comment]
@SvSven @padms @millianapia I removed the feature flags in a PR since this touches a significant amount of code. Please review it =)
