### ISSUE TITLE
Investigation task. Do we need separate template for local news type. (To allow access for unique editors to publish local articles)

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#143]
For now this is mostly for Equinor Venture, UK and US news on the global site. Could be the same template. No subscription option for these news.

**Comment by SvSven** [comment]
Documentation/sketching in Figjam here: https://www.figma.com/file/xm1aNey7RrP4llwou1t8OX/Envis-content-Figjam?node-id=1225%3A16123

To summarize:
- Use the same template as the normal news article, with a few adjustments
  - No subscription
  - Dropdown to select which market/tag
  - Adjusted slug field
- The slug field is prefixed by the country tag resulting in something like: `/uk-news/:slug`
- Split the Sanity 'news' menu into 2 submenus;
  - Global news (show all normal news)
  - Local news

For the local news we can use a filtered/smart folder approach where we can have the following options:
- Show all local news
- Filter news by market

Where the 'filter news by market' option gives the user an option to show news for only the specific market, similar to how the desk structure filters work for the asset library

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/027116f5-0823-4e6a-9bdd-0a165a9ac6a2)

With regards to the web part; the local news will not be part of the newsroom, instead they will create a dedicated topic page for each market where they want to add a new "news list" component. This component would work similar to the promotion component where they select a market/country tag which will then automatically generate a list of all local news for that market.

It might be good to create a proper "list" component for this instead of using the regular cards, something along the lines of this:

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/4c134d88-fe90-46de-939f-ff0656f8621a)

As question to be answered here is: do we want/need pagination for this list, or some kind of "load more" button - as this list should show **all** the local news for a market, since this will be the only place to find the local news.
