### ISSUE TITLE
Promo sections in promotion - link to another language

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1434]

**Comment by padms** [comment]
Looks good to me!👌👌

**Comment by meols** [comment]
@millianapia - is the task here to test people promotion only in the promotion component? Asking since I see the title has been changed from _promote people_ to more generic _promo sections_. The people promotion has the other language option and is working as it should :thumbsup:. For event, magazine and topic I don't see the Link to another language toggle.

**Comment by millianapia** [comment]
@meols the reason the title and the scope changed is due to that the promote people was the only component (of promotional) that had linking to begin with. If people promotion work as it should, i will be moving this forward

**Comment by meols** [comment]
Thanks @millianapia - people promotions works as it should :smile:
