### ISSUE TITLE
Implement breadcrumbs on pages

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1501]
Through both Comprend report and Bow and Craggs (two companies COM engages with for site testing, more angled towards content) We have received feedback on our menu and lack of sign posting on pages. One area that we should look into is implementing breadcrumbs onto our pages to indicate to users which section they are in and allow them to go back the main section without opening the menu. 

We would like to discuss this with the tech team on how best to solve and what options there are for automated breadcrumbs vs manual additions.

This should apply to TOPIC page template only

**Comment by SvSven** [comment]
So personally I like breadcrumbs and hate it with a passion when a site (or more specifically, a webshop) omits them - especially when navigating from search. That said I'm not up to date on what the Great UX Conclave deems of breadcrumbs these days. We also need to make sure they are designed/placed in a consistent way across the entire website. I think we should really have it automated and "hard coded" on the pages to achieve this consistency and placement, and not be up to the editors to say where they should be placed or what the content should be.

Other than that, it depends on what you want the user experience to be and how you want the content hierarchy to be displayed. The simplest and probably best option is to just use the menu structure rather than what the user has actually navigated, i.e. `Home > Energy > Renewable energy and low carbon solutions`. This should be fairly easy to implement because we have this structure in Sanity. Displaying the _actual navigation_ of the user  (e.g. `Home > Search > News > 2022 Q4 results`) would be possible, but it would be more complex and error prone, and I personally don't think this adds any value since it basically just mimics the browser's back button.

**Comment by NickHaggerty1** [comment]
@meols @SvSven Agree with most of that Sven. Automating/hard coding is the way to go for the most part and the menu does reflect our rather flat structure... There is occasions however where:
1. Pages are not in the menu but should still have breadcrumbs
2. Some pages do "belong" under other pages (despite being on the same level template and route) eg home / careers / graduates / **graduates-disciplines**. Its these pages where breadcrumbs would really help the user go back (to graduates in this example) This is where it would be good to be able to say override the breadcrumbs hard code and indicate an additional level...

**Comment by SvSven** [comment]
Maybe a good approach then would be to have a checkbox for "Override breadcrumbs" where editors can then select routes in a dropdown? That way we can assure that we have a link to a valid and published page.

Something like this:

 ![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/fd474af6-379c-4689-82f6-c110fd34db2c)

Still some quirks to work out with something like that, because you run the chance of then creating breadcrumbs like `Home > Sustainability > Sustainability > Hydro power` but I don't think we can make it 100% foolproof.

**Comment by fernandolucchesi** [comment]
What about making it very simple, such as:

![image](https://user-images.githubusercontent.com/23337266/219658862-8d94c2d8-307f-4509-b0fc-9cc01243331c.png)

**Comment by NickHaggerty1** [comment]
![Screenshot 2023-03-31 at 12.36.19.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/b27a559e-01c6-488e-9581-97c0ad9dca3a)

**Comment by NickHaggerty1** [comment]
@SvSven Breadcrumbs are on the Topic page template page. All the way to the right. Couple of text size options in place and indicated (The breadcrumb setting in EDS looks a little small to me but maybe we need to try it in the solution)

**Comment by SvSven** [comment]
@fernandolucchesi @millianapia @padms 

This can be looked at on technical side, there will probably be some back and forth regarding the design and spacing between the different header types since it doesn't quite look right/nice for some of them.

Created a new issue (#1587) for adding this to Sanity v3

**Comment by millianapia** [comment]
Looks good from what i can see, good work!

**Comment by SvSven** [comment]
@NickHaggerty1 @meols This can be looked at. I'm expecting some back and forth on the design part with the different header types, since we only really thought of the regular topic page with normal image style I think.

Breadcrumbs can be made on the topic routes in Sanity. It currently doesn't look _the best_ in the Studio, but it will be a lot better in version 3.

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/109b8d05-7c1b-4cc8-9559-9dba40537e8b)

Sneak peak of v3:

![image (10).png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/8076e2ea-a8b1-4846-b8ff-e1d139ad9115)

**Comment by NickHaggerty1** [comment]
@SvSven Approved. Great work.
