### ISSUE TITLE
Remove hyphens from breadcrumbs

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1623]

**Comment by nilsml** [comment]
Discuss with COM before starting this one

**Comment by padms** [comment]
@SvSven '-' is replaced only for the first occurrence. https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/no/test/test-padmaja-norwegian

**Comment by SvSven** [comment]
@padms Fixed the hyphen only being removed on the first occurrence and fixed the language filter

Not 100% sure what you mean with the 3rd point; the whole idea behind the custom breadcrumbs option is to allow editors to create whatever kind of breadcrumbs they want 🤷‍♂️ there's always a risk that the breadcrumbs make no sense, but that's up to the editors

**Comment by padms** [comment]
LGTM

**Comment by SvSven** [comment]
@fernandolucchesi @padms @millianapia So I added a new 'title' field to get around the issue with some words requiring a hyphen; took a lot of headscratching to make it backward compatible for a more seamless transition since the editorial team have already added a bunch of breadcrumbs - but I think this should fix it all.

**Comment by millianapia** [comment]
Looks good to me! good work
