### ISSUE TITLE
Optimize husky

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1654]

**Comment by SvSven** [comment]
@fernandolucchesi @padms @millianapia @nilsml 

This should improve the way our pre-commit tests work in that it only lints the files that are staged (that's the task that took up most time) and only runs other tasks if relevant files have been changed and staged.

There is still some room for improvement, for example only running tests for files that have changes but for some reason I couldn't get the `--findRelatedTests` flag for jest to work - though the testing task there doesn't take all that long anyway, so wouldn't make a big impact.

I was planning on adding type-checking for the studio and sanityv3 folders - however we first need to do some typescript fixing there, because it fails for both folders in their current state.

**Comment by fernandolucchesi** [comment]
Huuge improvement. Can you create an issue for adding it to v3/fixing typings there?

**Comment by fernandolucchesi** [comment]
LGTM ✅
