### ISSUE TITLE
Do not make empty search API calls to algolia

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1671]
Data shows that the most searched term on our website is empty. We should prevent our app from making empty search api calls, to reduce our usage.

<img width="400" alt="image" src="https://github.com/equinor/energyvision/assets/23337266/0ed37fe9-8983-475c-a52f-cf1d4af3915b">

**Comment by padms** [comment]
![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/f9fad969-4d99-4167-89c6-1fe1643232d6)

This should have fixed the empty search issue on search page.

**Comment by wenche** [comment]
You are probably aware of this already :) but remember that the empty search is the initial state for the news room ++ 👍

**Comment by padms** [comment]
> You are probably aware of this already :) but remember that the empty search is the initial state for the news room ++ 👍

@wenche True, news indices have the majority empty searches.

**Comment by padms** [comment]
Empty search on newsroom and magazine is unavoidable, otherwise no results will be shown and nothing can be filtered out of an empty result. 

https://www.algolia.com/doc/guides/search-analytics/guides/exclude-queries/#empty-searches

We are not sending empty searches on the search page, so we have done the maximum optimization.
