### ISSUE TITLE
As a user I want an intuitive menu structure so that it is easy to find the content I am looking for

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#186]
This issue cover menu milestone 1, which is the main structure of the menu. This first milestone will be a very simple menu with clickable links. 

Ability to define a menu structure consisting of 
- top level
- sub categories
- sub elements within a category

Acceptance criteria

- Hover the top level opens the mega menu (timing TBD)
- When clicking outside the menu closes
- Clicking a top level element opens the right overview page
- Categories are not clickable
- Clicking the sub menu elements opens the right sub page 

## In order to ensure good quality we should
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform user testing

**Comment by wenche** [comment]
Prioritize some mobile sketches for this :)

**Comment by wenche** [comment]
### Some comments on today's solution

The large version of the menu (desktop version) uses to actual navigation elements for each menu item. One for the actual link for a landing page ("What we are" in the image below) and one for arrow that toggles the actual sub menu. In addition, there's a hover effect on the list item that opens or closes the sub menu. The link to the landing page is also duplicated at the top of the sub menu.
![Skjermbilde 2021-08-16 kl. 12.13.45.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/a2d4af2b-098d-466a-a4fd-a6b4ca510b76)
 ![Skjermbilde 2021-08-16 kl. 12.15.53.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/840262ef-4171-4a8c-b55e-28da7450de88)
![Skjermbilde 2021-08-16 kl. 12.16.34.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/844801e1-5bc9-41eb-a1f3-31ef2412ba3c)


- If you are a keyboard user, you are able to both navigate to a top level menu item and to open and close the submenu. On the downside, you need to push `tab` twice for each item
- If you use a screenreader it seems to work because of this split into two elements and some aria labels
- If you use a mouse/pointer device, you'll see the hover effect and can click on the link to navigate or the arrow button to open close. If you accidentally  moves the mouse over the menu, the sub menu will open, but with a little delay so you'll see only one submenu
- If you are on a touch device, you can click on either the link or the arrow button

For the latter two, you have to figure out by yourself that it's actually two different action as no visible clue is provided in the design. This is not optimal?

Also you'll have the mobile version all the way up to 1199 px, probably because this makes it easier to get away with the lack of hover effects for pointer devices and to make it easier to use? Because the mobile version does not that this two action for each menu item feature. If you use e.g. an iPad Pro in landscape, the issue is the same. (Does not use media queries for pointer devices ++)

We need to figure out how we should do this in the new menu version.
1) Use the same (somewhat confusing pattern)
2) Revisit the UX pattern
