### ISSUE TITLE
Introduce tailwind and refactor portabletext

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2151]
Its seems that with portable text or something every <p> is wrapped in a div.
And headings is wrapped in a div.

These wrappers increase dom size and is unnecessary. 

rewrite to merge wrapping div styling into the tag itself

defaultSerializers should not use div containers. A text paragraph should be a paragraph.

**Comment by BorghildSelle** [comment]
@meols @NickHaggerty1 
https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/news/20230105-equinor-rwe-cooperation 

Can you take a look at the general look and the 2 headings used in that news article and let me know if the editorial team wants it even smaller?

I have suggested;
-  heading 2 styling in the "Strengthening energy security" that should apply for heading inside an article. 
- heading 3 styling in the "Driving forward". The h3 is a bit smaller, but with same fontweigth

**Comment by meols** [comment]
@BorghildSelle - in Equinor news articles in general we don't get the content from our stakeholders structured with a H2. If a H2 should be used to "introduce a new section/chapter" of content we are unsure if a H2 is suitable for the content. Wouldn't it be wrong to use a H2 when the content only is within the same topic? Our thinking is that H3 is more suitable as all content in a news article is subsections within the same topic. Is it critical to introduce H2 in news articles? If so, would it be better for screen readers to have only H2 headers instead of H3? In most cases all headers in the content are on the same level/within the same topic.

**Comment by BorghildSelle** [comment]
According to WCAG one should not skip heading ranks, because it can be confusing and should be avoided where possible. So a H1 should not have a h3 directly following but as the image below shows.

A page should have the title as h1, then the article should be sectioned into h2 headings as one would make chapters in a book. If one h2 heading is long it can be further divided into h3 headings.

Screen reader users can navigate a page according to its headings, listen to a list of all headings, and skip to a desired heading to begin reading at that point. 

![image](https://github.com/equinor/energyvision/assets/104756130/b7fbc10b-0e2b-4e0c-ac04-455cc286d4e8)

**Comment by BorghildSelle** [comment]
So you can dictate now how you would like a level 2 heading in an article should look like.
It will not affect the headings on other elements/components.
Only headings in an article (it can for instance also be applied for magazine, so that longer articles look the same)
