### ISSUE TITLE
Improve video accessibility

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2185]
Look into more accessibility options for video

- [ ] Does this video have captions? →
- [ ] Is this video audio-described? →
- [ ] Does video without audio have an accessible alternative? →
- [ ] Is there an alternative to the visual content in this video? →
- [ ] Can the audio be switched off? →
- [ ] Is it clear which page element has focus from the keyboard? →

**Comment by padms** [comment]
@meols  
We have replaced HSL video player, with VideoJS player. This affects all the video components. VideoJS player supports audio description track, which means we can provide audio described in screen9 console and the player automatically detects the track. <img width="1093" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1ZxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5cdbb521a35ad05d5c242116cf5d8c0db6d5bbfd/image.png" alt="image.png" />
I have provided a test track here in screen9 and the AD options shows on the video on my test page below. 
[Uploading... image.png]

Also instead of having the subtitles embedded in the video, we can add the subtitle track in screen9 console, which will show caption option in the player. This is helpful in cases where the captions get obscured because of the size of the video container. For example in my[ test page ](https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/videos), the captions are clipped in the looping banner video.

**Comment by meols** [comment]
Thanks for a very thorough answer @padms - this is a difficult/intricate topic to me :smile:
Very good that you have investigated screen9/quick channel - I assume more questions will come :wink:
(We have done manual checks in Siteimprove, but so far it seems that the issues are flagged as potential again at the next crawl.)
I suggest that we implement the updates/actual issues you mention above :thumbsup: - and we'll probably have more discussions on this topic.
