### ISSUE TITLE
image: create image component for rich text editor

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#224]
Related to #210

We can't use Sanity's focal point feature for images inside the rich text editor as they may be infographics, illustrations, or other figures.

**Comment by wenche** [comment]
@nicholas-haggerty @BirteThornquist (As discussed with Birte yesterday)

Adding photos to Sanity is split into several fields: The image itself, alt text, caption and attribution.
![Skjermbilde 2021-04-08 kl. 08.19.46.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/f94c7d8a-eba5-4829-b260-a5c355f674f7)

Since the attribution part is structured content, it makes sense to use a separate field. But in existing solution, this example will be written like
**Halfdan Brustad, vice president for Dogger Bank at Equinor. (Photo: Ole Jørgen Bratland)**

Are we able to create a rule for the attribution part so that the web can make a string along these lines
<Caption> (Photo: <Attribution>) where (Photo: and ) is "owned" by the web? From previous projects, this makes the texts to appear similar and predictable across the web page. Could it be (Video: Ole Jørgen Bratland) Do we need to prefix with "Photo" at all?

The other option would be to add  **Photo: Ole Jørgen Bratland**, **Video: Ole Jørgen Bratland** to Sanity (either ways I think the web would "own" the parentheses ( ) ) 

We should of course clarify this in Sanity by using a good placeholder og description.

What do you think?

**Comment by nicholas-haggerty** [comment]
Im not quite sure what you are asking. Happy to take a call.

**Comment by wenche** [comment]
Edited my comment slightly, the editor didn't show the complete example because I used code brackets...

I think the way forward is for you Nick to discuss this with Birte, she knows the details here :)

**Comment by BirteThornquist** [comment]
Having separate fields for Attribute and Caption is good. These should be optional and empty  - no predefined text/styles.

**Comment by BirteThornquist** [comment]
For the image component we will need some option; full column width, 50% column width either left or right alined. I will provide a sketch for this in Figma. We need to agree if these should be separate components (one 100% width and one 50% width), or variables of one image component.

**Comment by wenche** [comment]
Currently the max width is hard coded to 800px as we wait for the final article layout.

We will finalize this with issue #244 and #235
