### ISSUE TITLE
Fix korean characters overflowing news card 

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#2400]
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeENwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4646ee86b548d4095914deab9d84b0c93cdf5885/image.png" alt="image.png" />

https://www.equinor.co.kr/news

**Comment by BorghildSelle** [comment]
ill try to fix this in bose/2401-main with a word-break

**Comment by BorghildSelle** [comment]
did not work

**Comment by millianapia** [comment]
can not recreate in staging or main

**Comment by fernandolucchesi** [comment]
this showed up on my github feed and I couldn't help but take a look 👀 

`word-break: break-word;` should do the trick... You probably need to extend the tailwind cfg since it is not a default class, but seems to do the trick:

![image](https://github.com/equinor/energyvision/assets/23337266/fcb61cec-6d7d-4726-98fc-a2ccf9ed94d8)

![image](https://github.com/equinor/energyvision/assets/23337266/3ac15fee-7f02-4b42-8e6f-560ec26b796b)

**Comment by millianapia** [comment]
took a new try on recreating this in dev, finally managed to break it. Thank you for lurking @fernandolucchesi, your comments are always welcome <3 

extended the tailwind cfg and it worked like a charm

**Comment by padms** [comment]
@fernandolucchesi 👋

**Comment by meols** [comment]
Thanks Malin - approved :smile:
