### ISSUE TITLE
Adjustments to events promotion

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2414]

**Comment by meols** [comment]
Relating to the Events page: https://www.equinor.com/news-and-media/events we currently see just 3 upcoming events when expecting to see all upcoming events (currently 4).
How can we show all upcoming events?
Q4 analyst conference https://www.equinor.com/investors/q4-2024-analyst-conference isn’t showing, and when we add the press conference event for Q2 a week or so before 24 July, the Q3 analyst conference will disappear as well  – at least as far as we can understand. We will also add 3 (probably) events related to the ONS conference in August.
Could we have a field to select the number of upcoming events, as we can for past events? E.g. for the events page we should be able to show all upcoming events, and using the same settings (automatic) on the home page and be able to there select a number - 3 upcoming events - to show the 3 next events at any time without needing to consider the tag or selecting manually.

**Comment by millianapia** [comment]
need to add the carousel component for horizontal scroll when #2402 is completed @BorghildSelle

**Comment by millianapia** [comment]
@meols this issue is also connected to #2440. So if you approve this you approve the other. 

Now you can enter the amount of future events that will be shown - if empty, then all future events will be shown. 

Checkpoints
- You can choose amount of future amounts and the amount is correct
- if the amount of events are over 3 it should go over to a view in a carousel 
- If you choose 1 event, it should show the same view as when you toggle singleeventpromotion 

I also did some changes regarding the singlepromotion width, look below, 1. image is now, 2. is before

![Screenshot 2024-08-09 at 13 57 56](https://github.com/user-attachments/assets/8636333e-fee2-4656-be25-6bc1e54e9abf)
![Screenshot 2024-08-09 at 13 56 36](https://github.com/user-attachments/assets/ac058dc8-bad2-4ddd-b522-471426f82e1c)

**Comment by meols** [comment]
@millianapia - we see that for event promotion the Add to calendar button isn't showing if you haven't added location - which is optional. It is like this in production/live as well.
 <img width="1405" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDFpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f18f2e6c687151d15a6a96086eab1f1b8d21f76/image.png" alt="image.png" />

**Comment by millianapia** [comment]
this is unrelated to this issue, can you create a new issue for this, then i will look into this so it will be joining this in the next deploy? @meols

**Comment by meols** [comment]
@millianapia - will do! For the past events, can we show date (green "field"), title and location, instead of ingress (discussing with Nick now).

**Comment by BorghildSelle** [comment]
@meols the new way for past events is in the carousel branch actually
