### ISSUE TITLE
As a user I want different variants of the fact box

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#246]
### Must
1. Option for two columns (if a lot of content). Prefer some rules in the web for this, need to investigate
1. Option to include picture
1. Update title according to new design

### Should
1. Two different designs for the card (more/less air around text)

## In order to ensure good quality we should (Keep the ones we need for this US)
- [x] Perform integration testing
- [ ] Perform functional testing
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test

**Comment by SvSven** [comment]
- Text will be split up into 2 columns on larger screens (greater than 800px) if the factbox has no image and if the text has more than 800 characters.
- If the factbox has an image, the text will always be in a single column regardless of screen size. The factbox will be split in half, with 50% of the width being used for the image and 50% being used for the text.
- Editors are able to select which side of the factbox the image should be on (left or right, defaults to left)
- If an image has been selected, the height of the factbox will be default be determined by the height of the image; with a maximum height of 800px. If the factbox has more text content than fits within the 800px height, a scrollbar will appear for the overflowing text.
- If an image has been selected, editors can enable "dynamic height" which makes the text determine the height of the factbox instead of the image, up to a maximum of 800px. Dynamic height is disabled by default.
- For factboxes without an image selected, the text will always decide the height of the factbox, with no maximum height enforced.

Things that need to be looked at:
- Responsive image optimization
- Constraining the width of the single column text (when no image has been selected) to the body width of the news article. Is this something that is wanted/needed, how to constrain it, etc.

**Comment by SvSven** [comment]
TODO: move code for different variations from serializer to fact component in `web/components/src/Fact` & document options/variations in storybook

**Comment by wenche** [comment]
https://envis-storybook.azureedge.net/?path=/docs/components-fact--default
Page with a lot of facts: https://energyvision.app.radix.equinor.com/news/test-page

We have added some more variants in the storybook. It's hard to find the correct balance on adding a lot of use cases explicit vs control them in the canvas or play with it in the topmost component.

**Comment by wenche** [comment]
@vnys  Can you take a look at the negative margin stuff on this? Neither Sven or I could found something in git history. Do you have something local on your computer?

**Comment by BirteThornquist** [comment]
Seems like the Fact Box has a max width of 1920. It should be full width. Except form that, it is looking really good! Like we discussed earlier today, we will improve the way images are displayed in the Fact Box in a separate issue.

**Comment by vnys** [comment]
> Can you take a look at the negative margin stuff on this?

Yes, I’ll have a look at it

**Comment by petterwildhagen** [comment]
When viewing the factbox I get this every now and then:
![image.png](https://images.zenhubusercontent.com/60376a60b424c72d28d1572f/bf847c6f-7b62-4c26-8f41-369c44b865b3)

**Comment by wenche** [comment]
@petterwildhagen  I have noticed the same, but I don't think it's related to the factboxes. It's something buried deep down in the image library we use, and I haven't been able to find a pattern with when it occurs.

I think we must create a separate issue for this bug, and see if we are able to find the exact reason. It is somewhat related to client side navigation because everything works fine when you refresh the page.

**Comment by petterwildhagen** [comment]
@wenche 
https://app.zenhub.com/workspaces/energy-vision-5fb6386c578f1200222dd6c2/issues/equinor/energyvision/288

**Comment by vnys** [comment]
Can we stop using unnecessary breakpoints, please? 😅  I suggest _not_ splitting into two columns at some breakpoint with an arbritrary number, but when the lines get to long to read… That’s what’s important, not the width of the viewport.

**Comment by nilsml** [comment]
Did we conclude on this one? Are we removing the breakpoints or not? And what else remains in order for us to close this issue?

**Comment by petterwildhagen** [comment]
@nilsml  Will do a final check tomorrow.

**Comment by SvSven** [comment]
Created a new issue for the negative margin task: https://github.com/equinor/energyvision/issues/303

**Comment by petterwildhagen** [comment]
- [x] Text will be split up into 2 columns on larger screens (greater than 800px) if the factbox has no image and if the text has more than 800 characters. TESTED OK.
- [x] If the factbox has an image, the text will always be in a single column regardless of screen size. The factbox will be split in half, with 50% of the width being used for the image and 50% being used for the text. TESTED OK: SCREEN SIZE < 800 1 COLUMN AS EXPECTED AND IMAGE STACKS ABOVE TEXT.
- [x] Editors are able to select which side of the factbox the image should be on (left or right, defaults to left)
- [x ] If an image has been selected, the height of the factbox will be default be determined by the height of the image; with a maximum height of 800px. If the factbox has more text content than fits within the 800px height, a scrollbar will appear for the overflowing text.
- [x] If an image has been selected, editors can enable "dynamic height" which makes the text determine the height of the factbox instead of the image, up to a maximum of 800px. Dynamic height is disabled by default.
- [ x] For factboxes without an image selected, the text will always decide the height of the factbox, with no maximum height enforced.
- [ ] Things that need to be looked at:

Responsive image optimization
Constraining the width of the single column text (when no image has been selected) to the body width of the news article. Is this something that is wanted/needed, how to constrain it, etc.
