### ISSUE TITLE
Set up routing to create, render, and view topic pages

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#280]
**In order to view the careers page, we will set up the necessary routing**

## Acceptance criteria
<Yet to be determined>

## Sub-tasks
- [ ] Add basic schema for creating topic pages in Sanity (title, slug)
- [ ] Add routing in web to access / render topic pages

**Comment by nilsml** [comment]
In progress but no-one assigned. @wenche?

**Comment by wenche** [comment]
We are doing some experiments with the catch all route strategy and to have Sanity as the single source of truth for url. We are not sure if it will work, but we don't know that before we have tried!

[This article](https://www.simeongriggs.dev/nextjs-sanity-slug-patterns#slugs-in-nextjs) explains the idea pretty well

**Comment by wenche** [comment]
Since this is just an experiment to see if this could be a way to do things, we won't be spending much time on the slug field. But we need something more future proof and safe to use, that's for sure. It would probably be a good idea to make a custom fields, could for instance take some inspiration from the [Sanity's slug plugin.](https://github.com/hdoro/sanity-plugin-better-slug/blob/main/src/SlugInput.tsx)

**Comment by wenche** [comment]
It's not clear how language would fit into this picture yet. But that's a hard one to reason about since we don't yet know how to solve that. :)

**Comment by wenche** [comment]
We've done some experiments in the Studio with regards to the landing pages for each category. We need some special logic for /career, /what-we-do +++. Added a switch in the slug fieldset, but it's a lot of messy code in the slug format function. :grimacing: Since we don't know for sure if we will do it like this and still haven't nailed the studio content structuring, we decided to just stick with that for now and ask Sanity for some advices. 

Another option for structuring the content instead of this schema level approach can be to let the publisher's select the category manually. This is how we did it in the POC. We could then add a filter in the desk structure to easily navigate between the different categories.

**Comment by wenche** [comment]
Probably not so much to review here at this point. But we have implemented the idea from the article linked in the first comment. We want to try this approach as it has quite a few benefits with DRY. 

A couple of URLs are available as a starting point
/careers
/careers/experienced-professionals
/what-we-do
