### ISSUE TITLE
As an editor I want to add actions to the teaser component

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/energyvision#332]
Add a file 
Add a primary button

**Comment by SvSven** [comment]
Due to lack of description and designs in Figma, it's difficult to tell exactly what we needed here.
What I've done is that I have added the option to add either an internal or external link, a downloadable image, or a downloadable file similar to how we have the call to actions for the text block component.

Took a slightly different approach in the studio:

![image](https://user-images.githubusercontent.com/7661362/126461162-73c1bec6-63dd-4a7f-bf79-3d02e80cd709.png)

We can check whether this is a better or worse approach than we have for the call to actions and then adjust accordingly.

In terms of design for the web; we don't have a design for using a button as action on the teaser. There is one with the arrow pointing down for downloading a file, so I stuck with that. As a side effect of using that icon we now also have a hyperlink icon for external links which may be a good thing?

![image](https://user-images.githubusercontent.com/7661362/126463714-c4c2bcab-fc53-4c23-9d95-38718688e33a.png)

**Comment by wenche** [comment]
It's problematic that it's no feedback/validation for missing link? I didn't quite catch why one of the two original  teasers didn't show up in the web. The first one wasn't updated with the new link format, but no warnings

![Skjermbilde 2021-08-05 kl. 12.28.45.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/213e2270-7c74-44f1-8e6a-1c00c2f61007)

**Comment by nilsml** [comment]
Waiting for @SvSven's answer

**Comment by SvSven** [comment]
Hmm, strange. Might be I missed the validation - will have a look

**Comment by SvSven** [comment]
Fixed in https://github.com/equinor/energyvision/commit/b0fb024c44dc1ef73f484531cb6974d63b7defdc
