### ISSUE TITLE
Create an accordion component for the web

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#350]
**In order to collapse content, we need to create an accordion component**

The EDS accordion should be used as a basis.

## Acceptance criteria
_To be filled in by the team (need to agree upon features we need from an accordion component)_
1. Accordion state in the url
1. Accessible
1. Adhere to design from Figma
1. …

## Sub tasks
- [ ] Use EDS component and tailor for this project
- [ ] Implement in Storybook

**Comment by wenche** [comment]
We started out by using the EDS component, but it turned out to be somewhat difficult and would need a lot of style overrides since EDS has a white background. The hover effects doesn't play well with coloured backgrounds as well, and the use of the grey border around both the header and the panel doesn't play well with the rest of the Envis design.

**Comment by wenche** [comment]
Example in the web: https://energyvision.app.radix.equinor.com/careers/experienced-professionals?742af0675f87=0
Storybook: https://energyvision.app.radix.equinor.com/careers/experienced-professionals?742af0675f87=0

**Comment by wenche** [comment]
We need to review this and complete the design when Birte is back from vacation. :)

**Comment by BirteThornquist** [comment]
Great job - looking good! On hover the text should get bold.

**Comment by wenche** [comment]
Had a discussion with @BirteThornquist  on the hover effect. The issue is that when you change the font weight, the width of the text changes as well (since it is well, more bold). This will cause a "flicker" effect and this might or might not be something we can live with. 

We could tweak the animations slightly, but added only the  font weight 500 to test and see how that feels

https://envis-storybook.azureedge.net/?path=/docs/components-accordion--default

**Comment by BirteThornquist** [comment]
@wenche After testing this I see that in some cases the text will change from one to two lines on hover when we use the hover state bold on text - that is a bit too much. So, no bold effect on hover is the conclusion.

**Comment by nilsml** [comment]
@nicholas-haggerty

**Comment by vnys** [comment]
> Had a discussion with @BirteThornquist on the hover effect. The issue is that when you change the font weight, the width of the text changes as well (since it is well, more bold). This will cause a "flicker" effect and this might or might not be something we can live with.

@BirteThornquist This can probably be solved similarly to how Frida solved the menu item component in the EDS, by using an invisible element (a css pseudo element) where the text is bold so the text already takes up the place it needs when it’s bold.

**Comment by nicholas-haggerty** [comment]
@BirteThornquist @wenche @vnys I can certainly live without the title/question going bold. I think with the animation on the + / - button and the expanding line, its enough.

**Comment by nicholas-haggerty** [comment]
Following up. Victor mentioned that the new font provides some better solutions for animation between reg and bold so maybe that resolves this and we can feature the bold on hover without extending the text (posssibly on to two lines)
