### ISSUE TITLE
Investigate topic page route translations

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#375]
Related to #358

**Comment by wenche** [comment]
- Topic contents have page level translations using the intl-input plugin
- Topic contents are linked to routes by references
- At the moment we have one reference for the English content and one reference for the Norwegian one to make it easier to understand, both in code and for editors. We might be able to do something more automagic at some point and select the Norwegian content that belongs to the English content. But what it the Norwegian content doesn't exist when the Route is created?
- It's unclear which requirements the editor will fulfill to be able to publish a Route. Currently we validate both the English and Norwegian content as required
- Previews work for the selected language for Topic Content, and by selecting either the English preview or Norwegian preview for the routes.
- In the web we had to duplicate the query by slug because the preview plugin doesn't play well with param lang
- The query by id is extended to take the translated locale suffix into account, but is otherwise the same
- While things seem to work, it's quite fragile and can easily be messed up by editors. We have a couple of issues for this, like #384, #368, #380 and #308

We need to find a way to filter content for internal links to the selected language.
![Skjermbilde 2021-06-22 kl. 08.24.22.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/5637c700-145d-4522-98b2-de7113bcb303)

**Comment by wenche** [comment]
@nicholas-haggerty  I'm not sure exactly how this can be verified on your end since this is a pretty technical issue, and also a concept that may be improved later on. 

Maybe we should take a short walkthrough tomorrow?

You should now be able to visit [the English](https://energyvision.app.radix.equinor.com/en/careers) and [Norwegian](https://energyvision.app.radix.equinor.com/no/karriere) versions of the careers landing page.

(This is pretty complicated stuff, so I expect some bugs with this.)

**Comment by nicholas-haggerty** [comment]
@wenche Great lets have a walk through as part of todays meeting at 10.45. Ok for me to extend a bit if needed
