### ISSUE TITLE
Fix Storybook at CI

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#387]
**Describe the bug**
Storybook doesn't build in CI. Seems to be something with the blog storage

![image (10).png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/601aa05f-2f21-47a3-a61a-af8d199d0e9b)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vnys** [comment]
Azure Blob Github action updated. Also added a “Built at…” string on the front page (Introduction). This uses an environment variable that’s generated in the webpack config, and is only available in the preview part of the Storybook – meaning inside the iframe in the main content area. This makes it easier to see if the version of the storybook we’re actually looking it is the one we expect. 

There seems to be an issue with the CDN. where it’s clinging to old files even though they have been purged. The direct URL is https://envisstoragedev.z16.web.core.windows.net until this issue is resolved.

Most of the stories fail to build, which seem to be related to breaking changes in the new version we‘re using.
