### ISSUE TITLE
public folder in nextjs inaccessible on radix

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#390]
**Describe the bug**

**Comment by nilsml** [comment]
Can you check if this is good now @wenche?

**Comment by wenche** [comment]
I'm not sure if I understand exactly what's going on. Short story: I doesn't seems to work.

**Radix: (Some examples)** Missing favicon and fontawesome calendar symbol
![Skjermbilde 2021-08-10 kl. 13.02.35.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/baf38ca3-0eae-4217-b913-712fdc8e9f5c)![Skjermbilde 2021-08-10 kl. 13.02.40.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/613405ad-0f92-42da-8652-a3d7a4ff1a6d)
Url https://energyvision.app.radix.equinor.com/favicon-16x16.png:
![Skjermbilde 2021-08-10 kl. 13.03.40.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/201d2390-4d9d-44f4-9422-090503a3003f)

**Same examples on Vercel**
![Skjermbilde 2021-08-10 kl. 13.04.51.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/fd3a73c4-a4e4-4a71-8718-9ee25c874bd6)
![Skjermbilde 2021-08-10 kl. 13.04.54.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/82fc85d9-e13c-48e8-b029-5467cc897315)
![Skjermbilde 2021-08-10 kl. 13.05.29.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/74217900-1b16-481a-ac99-4d512acd37bd)


The Vercel one is the expected behavior.  I'm not sure exactly why this is different? Do you know Nils Magne aka The almighty DevOps Guru?

**Comment by wenche** [comment]
This tiny little ~~bug~~ feature was caused by that we don't listen to changes in the Dockerfile. 

Everything is working as expected now :)
