### ISSUE TITLE
How should the pages folder be in Next.js

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#450]
Evaluate different approaches for differentiating between static and dynamic pages

**Comment by wenche** [comment]
Added some pros and cons as a start in Figjam :thumbsup:

**Comment by SvSven** [comment]
Using the folder structure route of Next.js seems like the best approach for a couple of reasons:
- Separation of concerns; we don't have to mix the rendering and API code in the same file which makes it easier to keep an overview as well as easier to disable/remove the temporary static AEM functionality when the migration is done.
- Gives a clearer overview of which top-level routes are being served as static AEM content, and gives us better control over those routes. It also adds a safeguard where migrated content can be published in Sanity (either accidentally or deliberately) before the migration is complete since the folder structure routing always takes priority over the catch-all dynamic slug - so until we remove the folder route it will keep serving the static AEM content.
- We'll have some duplicate code, but we can minimize this by being smart about reusable functions and such. Even so this is probably still preferably over making a single file more complex and bloated by having it handle "everything".

All those things considered it seems like the folder structure routing is the safer and better approach for this, especially since we already have a proof of concept for it with the news archive.
