### ISSUE TITLE
Load legacy js for static topic pages

### ISSUE THREAD

**Issue by vnys** [equinor/energyvision#490]

**Comment by padms** [comment]
- Created a workflow to build and export legacy js to Azure.
- Used the script from Azure in the static page.

**Comment by wenche** [comment]
@vnys  Do you mind to just verify this? :)

**Comment by wenche** [comment]
@padms  We see weird things happening here as the page keep polling for the legacy script at regular intervals.

![Skjermbilde 2021-11-02 kl. 10.59.27.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/9e2feb8e-c117-4e06-8307-c8a96ae16c79)

This might also be the root cause for why we see this insane amount of duplicated class names?
![Skjermbilde 2021-11-02 kl. 11.01.01.png](https://images.zenhubusercontent.com/5fb7aa9
b653d5135bb8c50f5/6b1a8c65-2ab0-4c7f-ad9a-7d74cd38ae8a)

**Comment by SvSven** [comment]
For whatever reason the legacy-js cannot be loaded by using the `next/script` component as it breaks after navigation.
One solution was to add it with the useEffect hook. However since it doesn't have a dependency array, it will run every time the component re-renders. This is a "fix" for the scripts breaking on navigation.

Adding a dependency array to only have the hook run once will stop it from constantly requesting the script, but will also cause it to break again on navigation.

The classnames on the body are added by the Modernizr script which is included in the legacy-js bundle; since this script gets loaded "for the first time" (in its eyes) once the component renders, it will keep adding these classes to the body - causing such a big list.

**Comment by padms** [comment]
@wenche @SvSven used router.asPath in dependency list for useEffect. Its now polling only once when the router path changes.

**Comment by nilsml** [comment]
Can you review this one @vnys and sync with @padms if changes are to be made?

**Comment by SvSven** [comment]
Looks like it loads once per static page now, so it reloads when you navigate to a different static page. That's probably unavoidable and definitely an improvement at least.

Still adds the `modernizr` classes to the `<html>` tag every time it's loaded (so that stacks up), but again not as bad as it was. We may be able to do something to remove those classes before the script loads or something if it starts becoming bothersome.

**Comment by nilsml** [comment]
We can live with this for now.
