### ISSUE TITLE
As an editor I want to create tags so that articles can be filtered

### ISSUE THREAD

**Issue by adneforslund** [equinor/energyvision#526]
## Acceptance criteria
1. Create and add tags in Sanity Studio for news articles
1. Find a way to handle language
1. Create rules for tagging documents (how many, length, etc)

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by nilsml** [comment]
This is good, but perhaps you could add some more details on what this user story should cover? Put yourself into a tester's shoes; how can you verify that this user story is done?

And before you start working on this issue have a meeting with the team to go through different aspects so that we make sure we agree on the solution. @adneforslund

**Comment by adneforslund** [comment]
@nicholas-haggerty What do you think about the current solution?
