### ISSUE TITLE
Sanity DAM asset library needs  further investigation 

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#536]
When looking into the newly set up Asset library we notice several issues that need to be rectified

No warning when uploading a new file with the same file name as an existing file – should be able to replace with a new updated file, or choose to keep both, or as version
File name on hover in preview doesn’t show the uploaded pdf's filename e.g. sustainability-report-2020-pdf https://cdn.sanity.io/files/h61q9gi9/production/ef021e175cd8561245314bf1fcf264d4e8a57bd3.pdf
Seems like file name isn’t what’s unique, but Sanity gives a new “internal url” per upload no matter what the file name is. Can we then replace a file?
Uploading in an article you don’t choose where to upload to (smart folder) and can’t see other files when uploading (e.g. editors wouldn't know if the file already exists, leading to duplication)
No version history or upload version
Drag and drop not working – even if it seems to be possible
No pdf preview – which is useful both for adding description and confirming it’s the correct file
No published time, only Last updated
No info on which user that has uploaded/published
No options to publish a file from Media view (nice to have, useful when replacing a file that is in use on several pages)

**Comment by nicholas-haggerty** [comment]
First task is to reach out to Sanity support. I can do this but need contact details. I have no channel towards the Sanity developers. @SvSven can you please provide

**Comment by wenche** [comment]
@nicholas-haggerty  Use the Slack channel? You are a member in the shared channel

**Comment by nicholas-haggerty** [comment]
We have received response from Sanity in slack. Response below:
1. No warning when uploading a new file with the same file name as an existing file – should be able to replace with a new updated file, or choose to keep both, or as version
See also #3 for details on why the asset's file name is not (as) important in this case. It might be possible to do some validation checks when selecting a different asset inside an image field of a document, or as a document action when publishing that document. More information on this point is pending, but #3 gives it some context.

2. File name on hover in preview doesn’t show the uploaded pdf's filename e.g. sustainability-report-2020-pdf
Assuming you are referring to the URL preview in your web front-end and not in the studio, you can accomplish this to some degree by incorporating the file name at the back of the asset URL. The URL parameters will continue to work this way.General format:
https://cdn.sanity.io/images/<projectId>/<dataset>/<hashedFileName>/<vanityFilename>?<params>
Example:
https://cdn.sanity.io/files/h61q9gi9/production/ef021e175cd8561245314bf1fcf264d4e8a57bd3.pdf/sustainability-report-2020.pdf
3. Seems like file name isn’t what’s unique, but Sanity gives a new “internal url” per upload no matter what the file name is. Can we then replace a file?
You're right - on upload, we calculate a unique cryptographic hash based on the image itself. This ensures that even if you upload the same file again, it does not create a duplicate but instead uses the already available asset (with the same hash). However, this also prevents you from simply replacing an asset by uploading a file with the same file name, for example, as this would still produce a different asset ID (based on a different hash).Until we offer a better way, if you know the IDs of the old asset and the new one that you want to replace it with, you could run a migration script to update all relevant asset references and then delete the old asset if desired. Here's an example in this direction: https://github.com/sanity-io/sanity-recipes/blob/master/snippets/migrateDocumentType.js.However, an image might also have metadata such as captions, crops, hotspots, etc. that are specific to where the asset is used, as opposed to asset-specific. See also the difference between the image type output (specific use) and the sanity.imageAsset (global use) type output on this page: https://www.sanity.io/docs/image-type. Simply updating the asset _ref will not deal with the image type metadata. This is something to consider for any of these migrations.

4. Uploading in an article you don’t choose where to upload to (smart folder) and can’t see other files when uploading (e.g. editors wouldn't know if the file already exists, leading to duplication)Duplication is avoided because of the hash-based asset IDs described above: identical files will generate identical hashes and will therefore be ignored on upload.In terms of organization of files, you could consider using tags for this purpose. When assigning tags using the Media browser plugin, you can then easily find relevant assets using these tags. This does require editors to use the media browser as their asset source. An advantage of this approach is that a file can belong to multiple tags, which is not as easily possible without duplication when working with folders instead.

5. No version history or upload version
We do not currently support version history for assets in terms of replacing a specific asset and seeing that reflected in the asset document's history, as replacing the file means a new hash and therefore a different asset document. However, we do have document history to show changes of assets where the assets are actually used, e.g. in a blog post type. There should also be a way to see metadata changes on a specific asset document (sanity.imageAsset or sanity.fileAsset).

6. Drag and drop not working – even if it seems to be possible
This should indeed be possible (see the attached gif). If it is not working for you, could you confirm whether this is happening on an image field (i.e. not in the Media browser) and whether that image field may be inside a fieldset? Also, is this happening across different browsers for you?

7. No pdf preview – which is useful both for adding description and confirming it’s the correct file
It might be possible to work around this using a custom preview component - I will check if we have anything like that available.

8. No published time, only Last updated
The relevant (asset) document should have a _createdAt system field that you could consider the first time a document was created/published - or in this case, the first time the asset was added. The updatedAt value is when it was last updated/published.

9. No info on which user that has uploaded/published
Although this information is indeed not available on the document itself, you could see it by opening the asset document's history pane. However, this requires surfacing the relevant asset document in your desk structure. I don't think the Media browser plugin currently shows the information and am not sure to what degree it could. More information on this point is pending.

10. No options to publish a file from Media view (nice to have, useful when replacing a file that is in use on several pages)
I think having a way to globally replace a file makes sense. I will share this as a feature request with the team. It might work to have this option in the Media browser plugin. More information on this point is also pending.

Please let me know if I understood these issues correctly and if you have any remaining questions based on the above. (edited)

**Comment by SvSven** [comment]
The media plugin provides a better experience than what we get from Sanity out of the box, however there are still some features that are lacking even with that. Since it is unlikely that we will get these features in place in the time-frame we need (or even at all) we are faced with 2 different options:

- Fork the media plugin and customize it as best we can to get the features we need
- Go for an alternative approach using document types to set up a different kind of file structure for managing files such as PDFs and excel sheets

The first approach has a lot of unknowns and potential problems in the long run. We are not familiar with the codebase of the plugin and don't know beforehand what is or isn't possible, meaning we would likely spend a good chunk of time just figuring things out. In addition to this, the more changes we implement in our version of the media plugin the harder it becomes to maintain it in the long run, as merging in updates from the upstream plugin will become more and more difficult.

The second approach is therefor likely to be the better option as this gives us more or less full control of the interface and UX with regards to the editorial workflow, and since it's in a way similar to how we have set up the routing system it's a consistent way of doing things for both the developers and editors.

Having discussed this and showed a prototype of it to @nicholas-haggerty and @meols we agreed that this would be the best way forward since it allows us to tick off most if not all the points listed in this issue.

We do however want to be able to have the `source.name` and `source.id` be exposed within the media plugin for images, as this allows the editors to easily find specific images imported from Brandmaster; which is needed for GDPR reasons.

I put out a PR to the media plugin to do this, however this was declined to be merged in as it is deemed to specific to our use case. See: https://github.com/robinpyon/sanity-plugin-media/pull/56
We will likely be able to add this functionality to the media plugin itself at a later point as customizing filters and meta fields is on the roadmap, but there is no ETA on that - so until then the suggestion is to keep a fork of the media plugin locally where we have this feature enabled, but keep the customization to a very minimum so that we don't run into any issues in the long run; and then go back to the official version of the plugin once that is supported.

Screenshot below is an example of how the suggested file system would look like/work:
![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/56930b20-48ee-4934-baf5-38da79d5d080)
