### ISSUE TITLE
When opening the menu from an archived news item nothing is displayed

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#537]
Going through several news articles to verify tags and noticed that the menu/logo/search is in the top bar. However when opening the menu nothing is display other than to close the menu.![archived news article.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/930c8cb3-3d55-4c2e-839d-745d551c8534)

https://energyvision.app.radix.equinor.com/en/news/archive/press-release-1q-2016

**Comment by wenche** [comment]
@nicholas-haggerty  That's the bug I was talking about earlier today #517 :)

It was fixed at that point, but I can see that you reintroduced this bug by adding the Heading component back in @padms https://github.com/equinor/energyvision/commit/7e81103fe2c278eb6b5b58efe599aea42c8ff6eb#r58344488 Could you please remove it and commit? Since you are working in the file :thumbsup:

**Comment by wenche** [comment]
@nicholas-haggerty "Aldri så galt at det ikke er godt for noe", as the common Norwegian sayings. At least you have a better understanding of #517 by now
