### ISSUE TITLE
Caching and CDN for static content

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#553]
Putting a CDN in front of Azure Blobstorage lets us control cache headers more easily. This will improve user experience when accessing static pages.

**Comment by padms** [comment]
Trying to purge the cdn content whenever it changes. Testing the purge api.

**Comment by nilsml** [comment]
[New app registration with service principal](https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Overview/appId/14368378-aefd-43e0-9ea8-1fb6c13cb8ca/isMSAApp/) created for testing this out.

Before closing this issue, remember to:
- [ ] Rename app registration
- [ ] Restrict permissions properly

**Comment by padms** [comment]
On debugging, the fetch api always fetches the cached content without revalidation. So added 'no-cache' directive in the fetch call.

**Comment by padms** [comment]
After the publication today, I could identify one issue.

Below are the links to news article published and updated with in short time. The Norwegian version has same content as that of production. But the en version still has the old content which means the scraper extracted the content even before production has invalidated data. 
https://web-energyvision-dev.radix.equinor.com/news/archive/fourth-quarter-2021-results-and-capital-markets-update-2022
https://web-energyvision-dev.radix.equinor.com/no/news/archive/fourth-quarter-2021-results-and-capital-markets-update-2022
https://www.equinor.com/en/news/fourth-quarter-2021-results-and-capital-markets-update-2022.html
https://www.equinor.com/no/news/fourth-quarter-2021-results-and-capital-markets-update-2022.html

**Comment by padms** [comment]
Static content was getting old content from CDN, after adding 'no-cache' directive to the fetch API call, the latest content is delivered.  

So, the static content will atmost take 5 mins ( as revalidate = 300 , set in next js getStaticProps)

**Comment by padms** [comment]
@nilsml I deleted the app registration as it is no longer needed.

**Comment by nilsml** [comment]
Good @padms. I guess the permission were deleted wit the app as well

**Comment by padms** [comment]
@meols Need your help in understanding if the issue still exists.

**Comment by padms** [comment]
@meols  I made changes to update the pages containing LatestNews when a news article is published.
At the moment the following pages along with the home page are set to update when a news is published.

            "/what-we-do/johan-sverdrup",
            "/media-centre",
            "/investors",
            "/where-we-are/united-states",
            "/what-we-do/floating-wind",
            "/where-we-are/european-union",
            "/what-we-do/renewables-us"

**Comment by padms** [comment]
The pages containing dynamic components like LatestNews, Magazine List, Loop article will update themselves automatically in AEM whenever an article is published. The scraper tool is not notified of this change unless the page is published again. So scraper tool is modified to fetch the pages containing dynamic components when the page published is a news. We need to update this pages list in the scraper tool for Loop Article and Magazine articles.

**Comment by meols** [comment]
Thanks @padms - just to be sure, when you say "update the pages containing LatestNews when a news article is published", that means that the news list is updated, but the page itself isn't published - correct?

**Comment by padms** [comment]
@meols Yes Mette..

**Comment by meols** [comment]
Great @padms - we'll check the time it takes for the next news publishing(s)

**Comment by meols** [comment]
@padms - I just noticed that the two latest news from .com aren't shown on the front page:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/e2bccadc-0016-4036-80bc-7e56626a205e)

**Comment by meols** [comment]
@padms - we published a news this evening at 19:44. It still isn't visible on the Sanity frontpage at 22:00, and we now have the three latest news from AEM not showing in Sanity. 
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/5cf73c95-36d6-4de5-a3a6-062d0fbf9b35)
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/914da29e-8f01-481c-9298-1b2928e23829)
(I have not published the Sanity frontpage)

**Comment by fernandolucchesi** [comment]
Turns out that the CDN cache has to be purged for the new content to be updated. The approach to fix it was handled in Azure, instead of making API calls from the Java code.

1. An EventGrid was created ([CDNPurgeEvent](https://portal.azure.com/#@StatoilSRM.onmicrosoft.com/resource/subscriptions/a8b981a0-f92f-452c-90dc-d1226778e182/resourceGroups/EnvisRGDev/providers/Microsoft.Storage/storageAccounts/envisstoragedev/eventgrid)) that is triggered every time a blob file is created or deleted.

2. The event calls a webhook ([CDNPurgeWebhook](https://portal.azure.com/#@StatoilSRM.onmicrosoft.com/resource/subscriptions/a8b981a0-f92f-452c-90dc-d1226778e182/resourceGroups/EnvisRGDev/providers/Microsoft.Automation/automationAccounts/EnergyVisionAutomation/webhooks/CDNPurgeWebhook)) that triggers a [Runbook automated process](https://portal.azure.com/#@StatoilSRM.onmicrosoft.com/resource/subscriptions/a8b981a0-f92f-452c-90dc-d1226778e182/resourceGroups/EnvisRGDev/providers/Microsoft.Automation/automationAccounts/EnergyVisionAutomation/runbooks/CDNPurge/overview)

3. The Runbook script (go to the runbook page and click on 'Edit') gets that filepath, checks if file should be purged or not, and purges it if needed.

We decided to not purge files that are inside `/content/dam` and `/etc.clientlibs` since they are mostly image assets. To cause a similar "purge effect" for images we can simply re-upload them with a different name.

**Comment by fernandolucchesi** [comment]
@nilsml can you review this one? I can assist demonstrating the flow and the logs if needed

**Comment by nilsml** [comment]
This sounds like a sweet solution @fernandolucchesi and @padms! I have one important question though: do we have the code for all this checked in to Github and deployment set up? We need to make sure we can redeploy at any time.

**Comment by fernandolucchesi** [comment]
> This sounds like a sweet solution @fernandolucchesi and @padms! I have one important question though: do we have the code for all this checked in to Github and deployment set up? We need to make sure we can redeploy at any time.

Hi @nilsml, this is a very nice to have! I have just created an issue for that #897.

**Comment by fernandolucchesi** [comment]
Looks like it is working fine, closing this issue.
