### ISSUE TITLE
As an editor I want to update slugs so that can change the site structure or fix typos

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#555]
Editors should avoid to change the slugs, but in some cases it is necessary. Like in the case of a typo in the slug or a change to the site structure.

## Acceptance criteria
1. Update the slug in Sanity
1. The old slug/url will redirect to the new one

## Technical notes
This is (yet) not very well handled by Sanity. Even if they do save the old slugs in the slug field (that's why the latest one is retrieved by `slug.current`) there is no way to access previous versions from the API. See https://equinor.slack.com/archives/C01A4BGNRMJ/p1629285924033300

**Comment by fernandolucchesi** [comment]
@meols this issue is related to slugs being indexed by google, and then changed by an editor afterward. The old slug should then redirect to the new one so we don't lose the ranking score. This can be done by manually creating a redirect, this issue is related to automating it. Do you think it is necessary? IMO it is not worthy it.
