### ISSUE TITLE
Warning for "missing width" for images with Next 12

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#575]
With Next 12, we see a lot of warnings in the console for missing width of the images.

![Skjermbilde 2021-11-03 kl. 09.26.28.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/49f33a22-6287-4d4c-beae-5e02b03dcfec)

**Comment by wenche** [comment]
This issue is because of the next-sanity-image plugin we are using and [they have an open issue about this in the repository](https://github.com/bundlesandbatches/next-sanity-image/issues/23)

**Comment by SvSven** [comment]
Upgraded to v3.1.8 which should fix this issue, but I'm still seeing the warnings. Will investigate further to see if there is something in our implementation.

**Comment by SvSven** [comment]
I can't figure out the problem in this, it seems like there are issues with at least:
- Topic page hero image
- Image component (both full-width and not full-width)
- Quote image

While it doesn't seem to happen with at least:
- Teaser image
- Promotion card image (news and topic)

There is no clear difference between how these images are implemented, but the results are consistent so there is clearly _something_ going on there. Doesn't seem to be a problem with a specific document either, because the same happens when creating a new topic page.

**Comment by wenche** [comment]
There's no warnings if we create an image without the option callback with Sanity ImageUrlBuilder. When the options object is added, even with the most basic example from the docs, the warnings show up. 

I have asked Sanity for some input on this and they will look into this

**Comment by wenche** [comment]
Opened another issue in the plugin lib
https://github.com/bundlesandbatches/next-sanity-image/issues/31

It was not that easy to just fix this at our end.

**Comment by wenche** [comment]
So... Dead silence. I'll spend some time just to see if we can remove this lib all together

**Comment by wenche** [comment]
Too much work for now to remove the lib IMHO. I have suffixed with at width, it shouldn't actually affect the image pipeline of Sanity but still makes Next.js happy. Let's see if it's updated in the library at some point, but closing this for now. OK @SvSven ?

**Comment by SvSven** [comment]
I can't see the warning in either the browser console or the server console, so looks to be fixed by this 👍
