### ISSUE TITLE
As editor we will need specific components that are only needed on one page. Categorize differently on the component library? 

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#584]
In order to keep the Component library/list clean, can we group together certain components that may only have a single or very limited use? Under a unique title eg _special components_

For example: 
Cookie Declaration script:
The cookie declaration script tag should be inserted as is at the exact location where we want to show the declaration. So, we need a component to load this cookie declaration in order to load the cookie declaration Global and on other satellite sites too.

Stock Market info.

REMIT (if needed)

Source code (currently used to solve twitter feeds: https://www.equinor.com/en/where-we-are/united-kingdom.html)

+?

**Comment by nilsml** [comment]
All but the source code one should be covered now. We need to find a way to handle twitter feeds.

**Comment by wenche** [comment]
> All but the source code one should be covered now. We need to find a way to handle twitter feeds.

This is not what this issue is about. This issue is about categorising the more specialised less used components inside the Sanity studio component array, like we do for the promotions. We also wanted to add the title and ingress the way it is done for the promotions to make things more consistent . :)

If we do this, the list will be easier to navigate and adding like a twitter component will still only require one extra click.

It might be hard to create this without some data migration tho if the data structure changes.

**Comment by fernandolucchesi** [comment]
@NickHaggerty1 could you elaborate a bit more on this one? Is this still needed?

**Comment by NickHaggerty1** [comment]
@fernandolucchesi Think this was a Wenche request. Based on her comment above. I guess we have solved this? Either as she suggested or another way? Think I will just close it @meols FYI
