### ISSUE TITLE
Create the web part of subscribe form

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#590]
https://www.equinor.com/en/about-us/forms/subscription.html  - News subscribe form
https://www.equinor.com/en/about-us/forms/magazine-subscription.html - Magazine subscription form
https://www.equinor.com/en/about-us/forms/crude-oil-subscription.html - Crude oil subscription form 
https://www.loop.equinor.com/en/about/forms/loop-subscription-form.html - Loop article subscription form

**Comment by padms** [comment]
Based on the type field of the Subscribe form component, the categories checkbox should be shown. 
 Subscribe form has First Name and Email input fields , besides categories checkboxes based on the subscribe form type as follows : 
1) News type -> Stock Market Announcements , General News.
2) Crude oil assays -> No category checkbox. 
3) Magazine -> All stories , People
4) Loop Articles -> No check box.

**Comment by padms** [comment]
@nicholas-haggerty Could you please share some sketches of forms.

**Comment by nicholas-haggerty** [comment]
@padms Hey. Just checking with Brandmaster on whether we can solve this simpler so we don't have to have 4 separate subscription forms. Be great if the mail group is assigned to the choice the use the makes rather than which form they fill in...

**Comment by nicholas-haggerty** [comment]
![equinor-subscription-form.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/d129d4c2-0722-474b-b0dd-ac9ccd41a989)

**Comment by nicholas-haggerty** [comment]
![equinor-subscription-form-2.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/3f7baa1d-f953-473d-bcfe-f0ce8921e884)

**Comment by padms** [comment]
@nicholas-haggerty  There are two options under magazine subscriptions ( All Stories and People ).

**Comment by nicholas-haggerty** [comment]
@padms Yes I know. We will remove the PEOPLE choice

**Comment by wenche** [comment]
![Skjermbilde 2021-11-26 kl. 10.24.19.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/9e1aec46-caa2-4ba6-ad0f-9451d0e2fc3a)

Suggestion: Semantically speaking this should be a fieldset with categories as legend

**Comment by wenche** [comment]
/careers/students for example

**Comment by padms** [comment]
@nicholas-haggerty @meols Could you please take this further with Brandmaster? When the changes from their end is ready, we could test the working of the subscription API.

**Comment by padms** [comment]
@nicholas-haggerty  @BirteThornquist Could you also provide the sketch for showing the error when none of the checkboxes is checked?

**Comment by BirteThornquist** [comment]
@padms [Here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=3549%3A74908) is the sketch for error validation for the categories checkboxes. I have added a section header and a help text. If no checkboxes are selected the help text turns red with the same error filled icon as used in the text fields.

**Comment by padms** [comment]
@nicholas-haggerty Please review this.

**Comment by wenche** [comment]
I suggested some improvements for a11y on Slack. We really need to nail this one :muscle:

As discussed we also noticed an issue with the checkbox columns on smaller devices that caused the form to overflow outside of it's boundaries. 

This issue is only for the actual form right? What about the final creation of the api with the brandmaster stuff - do we have a separate issue for that?

Lot's of console.log statements :)

**Comment by wenche** [comment]
We should probably also remove the default `fieldset` padding and margins as we don't use spacing like that anywhere else in the code base :thumbsup:

**Comment by padms** [comment]
@wenche Corrections done as suggested in slack. 
The API part is still pending.. Not able to test at the moment. so commented it. I will resume once Brandmaster gives update on it.

**Comment by padms** [comment]
@BirteThornquist I made the changes.

**Comment by BirteThornquist** [comment]
Looking good @padms ! The vertical spacing between the checkboxes is a bit big. Can you take it down one size pls? I have also changed the heading [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=3309%3A71064)

**Comment by BirteThornquist** [comment]
Great @padms - good work! Guess this issue can be closed now...?

**Comment by wenche** [comment]
-Change to legend
![Skjermbilde 2021-12-13 kl. 08.13.07.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/102fed65-5f3a-41c7-9e8d-49b46b8cb13b)

- Only the checkboxes have aria-describedby, the input fields also need this because to comply with a11y we need a way to inform the user about the error
- The focus on error is not consistent between keyboard and mouse. If I don't fill in any of the fields and use my keyboard to submit, focus is moved to the first checkbox. If I check one of the boxes and hit submit again (still using keyboard) focus is moved to the first text input field. This is correct, the best way to do it.  if I use my mouse, there's no focus. 
- It's a strong recommendation a11y-wise to mark mandatory fields, either on a per field basis or by saying something about all fields being mandatory. Even if the design does not have this, we should use aria-required to mark the fields
- Sorry if you were confused by my js files in the api for preview, that was just copy'n paste to make things work. You should use typescript for the subscribe-form file.
- I do agree with Nils Magne about the location of the subscription, it should not be in the components folder. Do you think it will make sense to move it to the api as this is actually the api logic?

We should test the form by using a screen reader.

**Comment by padms** [comment]
@wenche 
 - Only the checkboxes have aria-describedby, the input fields also need this because to comply with a11y we need a way to inform the user about the error -- _Should this be part of EDS TextField Component? I am not able to add id to helper text element. _ 
- The focus on error is not consistent between keyboard and mouse. If I don't fill in any of the fields and use my keyboard to submit, focus is moved to the first checkbox. If I check one of the boxes and hit submit again (still using keyboard) focus is moved to the first text input field. This is correct, the best way to do it. if I use my mouse, there's no focus. _After I submit the form with no details, the focus is on the first checkbox, only that the dotted lines around the checkbox is not shown. Did I miss something here?_
- Sorry if you were confused by my js files in the api for preview, that was just copy'n paste to make things work. You should use typescript for the subscribe-form file. _I will convert it to typescript_
- I do agree with Nils Magne about the location of the subscription, it should not be in the components folder. Do you think it will make sense to move it to the api as this is actually the api logic? _I will move this to api_

**Comment by padms** [comment]
Created #666 for addressing the accessibility issues with text field component.

**Comment by nicholas-haggerty** [comment]
@nilsml Can you take a look and close when you get a chance

**Comment by nilsml** [comment]
I have reviewed the code. Looks ok to me. Gave some feedback while reviewing about environment variables missing from template files. Also we should consider error handling as this is now just console.log statements that we don't have access to in production. But that is part of a bigger task.
