### ISSUE TITLE
Create web part of event template

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#601]
Depends on #598

**Comment by wenche** [comment]
@SvSven  Can we assume that this is no longer blocked since it is in review?

**Comment by wenche** [comment]
@SvSven  Are we sure that we need an additional `event` folder in the pages folder for events? We talked about just solving this in the same way as with the Landing pages? E.g. create the content, add to a route and let the web see which template to use. Even if the requirement is to have all events published under the /event top level route, that could be solved by the create route? I'm worried about the extra duplication in the pages folder and that we no longer have a separation for news and "the rest" in the way they create content? Did you discuss this with someone? Am I plain wrong?

**Comment by SvSven** [comment]
I've refactored it to use the catch-all set up we have now, but still currently using the slug similar to the news pending discussion on how we want to solve that.

**Comment by SvSven** [comment]
@BirteThornquist This should be ready for design review now, the date and time are still missing but being worked on.

**Comment by BirteThornquist** [comment]
Looks good @SvSven! Two comments:
- the people promo component should have an optional title
- there shall not be an option to select a background color for the iFrame in the event template

**Comment by SvSven** [comment]
@BirteThornquist There is now an optional title for the people promo and the background selector for the iframe has been removed 👍

**Comment by nicholas-haggerty** [comment]
@SvSven @BirteThornquist Very good. I set the page up below and seems like there some spacing issues on PREVIEW and website. Bigger than spacing between components. Doesnt seem to be related to missing text fields.

https://equinor.sanity.studio/desk/event;5d90217b-c428-4d38-a8bf-703f78a767bb%7C%2Cview%3Dpreview

**Comment by BirteThornquist** [comment]
I see the people promote header is not left aligned as done in Figma, but in the middle @SvSven...

**Comment by nicholas-haggerty** [comment]
Also raised as an issue in #636

**Comment by nicholas-haggerty** [comment]
@SvSven Looking good. Im ready to shut this DOWN. @BirteThornquist any final comments?

**Comment by BirteThornquist** [comment]
Hi @padms I think the subscribe form looks a bit messy like it is now![Skjermbilde 2021-12-09 kl. 10.19.50.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/d12dd394-0457-40b5-8341-94951d145dfe) 
I think we should change the check box columns into 2 instead of 3. I also added a selection "all". Texts are floating too much together, so we'll remove the help text and rewrite the sub header instead. The error text will only show up on validation. I have updated the  [Figma design](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=3549%3A74908).  
I also noticed that the validation error text has an icon that shall not be there - only use the icon inside the text field. And the color for the error text should also be the "clear red 100". 
![Skjermbilde 2021-12-09 kl. 10.30.09.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/2e124244-d8d6-428d-b125-b1da10a187d1)

Seems like there is not the right padding (space) after the subscribe button...? Maybe you have used float?
![Skjermbilde 2021-12-09 kl. 10.39.02.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/206046fe-2685-4cf3-bb09-b085081f1611)

Just a final little detail - could the check boxes be left aligned same as the text fields? I know there is a clickbound, but could they be wrapped in a way to get them aligned?

**Comment by SvSven** [comment]
@BirteThornquist wrong issue 😅
But I copied your feedback over to the right issue: https://github.com/equinor/energyvision/issues/590#issuecomment-989692291

**Comment by BirteThornquist** [comment]
Oops - sorry! Thx @SvSven

**Comment by BirteThornquist** [comment]
@SvSven There is something happening with the padding/alignement .... Look at the Contact and Event list in the example attached:
![Skjermbilde 2021-12-09 kl. 11.54.42.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/4797c529-ddf0-4120-9116-e90f4d8b6ac7)

**Comment by SvSven** [comment]
@BirteThornquist Should be fixed now 😬

**Comment by BirteThornquist** [comment]
@SvSven The alignment looks fine now! But the headers h2 have different font sizes....?
![Skjermbilde 2021-12-09 kl. 12.30.47.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/b3131a83-7820-46e6-95f9-f8e10bffa09c)

**Comment by SvSven** [comment]
Hmm, yeah that is likely because of inconsistencies between the different templates (news, topic page, event).
I'll have a look to see what could be the best way of addressing that.

**Comment by SvSven** [comment]
@BirteThornquist The headings for the contact list and related content should both be set to the same size as the iframe and people promotion now (size XL), which is consistent with the topic pages. We might run into this issue again when we have another look at the news template, but we'll deal with that then 😅

**Comment by BirteThornquist** [comment]
Great @SvSven. Looking good! I'm closing!
