### ISSUE TITLE
Tags for the event

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#628]
## Acceptance criteria
- Separate tags for events
- Tag functionality exists for the Events template
- [ ] Update editorial documentation

Refer to comment below for suggested solution.

**Comment by fernandolucchesi** [comment]
Waiting for clarification on how event tags should work

**Comment by fernandolucchesi** [comment]
In order to be able to re-use same tags for different document types, while preventing bloating the editor's dropdown with a lot of unrelated tags for a specific topic, we came up with the solution of **adding a multi select input to each of the tags**, so that we can filter up which tags we display for each document type, while keeping its re-usability potential.

This approach also gives us flexibility in the website by allowing us to filter by 'types', 'tags', or 'types and tags'.

It is also crucial that we validate the removing of a "type value" from a "tag". We should not allow removing values that are being referenced by an existing document.

Sketch:
![image](https://user-images.githubusercontent.com/23337266/145391451-6e57abde-243d-48c3-a45e-0747bdb20506.png)

**Comment by fernandolucchesi** [comment]
@BirteThornquist please review the above description

**Comment by BirteThornquist** [comment]
The description looks good to me @fernandolucchesi!

**Comment by meols** [comment]
@fernandolucchesi - can we please look into this one in the next sprint?

**Comment by fernandolucchesi** [comment]
Sure

**Comment by SvSven** [comment]
@fernandolucchesi @padms @bhavi25 

This is ready for review, I didn't add any feature flags for it since the feature was already there with dummy tags, so not sure if we need it featured flagged or not.

It works the same as the tags for the news, local news, magazine, etc - we can create and manage tags under "Settings" in the Studio.

**Comment by padms** [comment]
@SvSven Event promotion are not filtered based on event tags.

**Comment by SvSven** [comment]
@padms Are you sure? They should be filtered 🤔 https://github.com/equinor/energyvision/blob/main/web/lib/queries/common/pageContentFields.ts#L309

**Comment by padms** [comment]
@SvSven I think so, but it is confusing that when I select past events and select tags, they are not filtered.

**Comment by SvSven** [comment]
Ahh yes, you were correct - I forgot to add the filter to the query for past events. Have fixed this and refactored the structure of the code a bit.

Should be working now 👀

**Comment by padms** [comment]
@SvSven Is always empty when no tags are selected.

**Comment by SvSven** [comment]
@padms it should now work again without tags - I don't like the way I had to solve it but I don't think there is a better/cleaner way of doing it in Groq 😕

**Comment by padms** [comment]
@SvSven I see two different results for same event promotion configuration.  Test content here https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/topicContent;f2969c65-a7eb-4b3e-aef2-c8c9a00314be

**Comment by SvSven** [comment]
@padms preview should be fixed now

**Comment by padms** [comment]
@SvSven Preview error is fixed. But there are no cards when tag filters are not applied.

**Comment by SvSven** [comment]
@padms The problem seemed to be that the promotion had event tags before, but were then removed - which meant that Sanity still had the `tags` array defined, but it was empty. Not the first time we've had that annoying problem.

Since GROQ doesn't seem to have a way of checking for length of the array, I added another toggle that the users will have to select in order to add a tag filter - that gives us a more robust way of using the right subquery.

Not super happy with the UX of this component in the Studio, but at least it works now - or at least it should.

**Comment by padms** [comment]
@SvSven Does not work now for Past events without tag filters. 
Test content here https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/topicContent;f2969c65-a7eb-4b3e-aef2-c8c9a00314be

**Comment by SvSven** [comment]
This issue is going to be the end of me 🙈

**Comment by SvSven** [comment]
@padms I think everything should be working now? Looks like I missed adding the new `useTags` conditional for past events.

Everything looks to work here: https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/event-promotion

**Comment by padms** [comment]
@SvSven Perfect

**Comment by SvSven** [comment]
@meols @NickHaggerty1 Tags! For events! Event tags! It's only taken 11 months 😅

You can test the tags for the event promotion here: 

studio: https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/topicContent;fdd230ac-17f6-4f93-8d36-e486496047bc%2Ctype%3Dpage

web: https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/event-promotion

And you can create/manage them in the same way as the other tags: https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/settings;eventTags

**Comment by meols** [comment]
Thanks @SvSven - great, fantastic, amazing and approved - and you can now stop dreaming about event tags in nightmares :smile:

**Comment by meols** [comment]
Thanks @SvSven - great, fantastic, amazing and approved - and you can now stop dreaming about event tags in nightmares :smile:
