### ISSUE TITLE
update pnpm in Docker file

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#681]
The lint, deploy and test action reports of an outdated pnpm version. We should upgrade this. Can this manually task be improved somehow?

![Skjermbilde 2021-12-20 kl. 08.32.47.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/cc95785c-f8ab-4af5-9251-4e9d6e5743e3)

**Comment by fernandolucchesi** [comment]
Hi @wenche, can you review this one?

**Comment by wenche** [comment]
I'm not sure if I understand this 100%. This is what I see :sweat_smile:

In [the workflow for the web](https://github.com/equinor/energyvision/blob/main/.github/workflows/web.yaml#L29), we use `latest`.  [That gives us 6.29.1](https://github.com/equinor/energyvision/runs/5005620209?check_suite_focus=true#step:3:19) which is indeed the latest according to pnpm's Github repo
![Skjermbilde 2022-01-31 kl. 19.18.07.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/747f0247-738b-4d61-8aea-d383153e9bfb)
In the Dockerfile, [you just updated to the latest](https://github.com/equinor/energyvision/blob/main/web/Dockerfile#L3). However, in the middle of the file [we still hardcode](https://github.com/equinor/energyvision/blob/main/web/Dockerfile#L34) (Do we need to install twice?)

**Comment by fernandolucchesi** [comment]
I actually missed this the one in the middle of the file. And yes we need it twice because they are different stages, and each stage are independent from each other. 

Idea behind multiple stages is to bring down the image size, so in the first one we have the folders + the built version. In the second stage we copy just the built files from the first stage and run it.

https://docs.docker.com/develop/develop-images/multistage-build/
