### ISSUE TITLE
Investigate how to handle home pages in sanity

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#703]

**Comment by fernandolucchesi** [comment]
> Please provide more info @fernandolucchesi to this issue if someone should test or verify it!

I forgot to link, there are some discussions happening in https://github.com/equinor/energyvision/pull/724

**Comment by wenche** [comment]
Lot's of discussions in #724

I have updated the description in #664 with the suggested approach by @BirteThornquist to make it easier to prioritise this feature.

In the meantime, I'm not sure if we should merge the PR or not? I would actually say no, since this is an investigation task and tbh none of the suggested approaches (PRs) were 100% in terms of functionality and UX. The publishers haven't started to create the home page yet either.

What do you @fernandolucchesi @adneforslund @SvSven @nilsml
