### ISSUE TITLE
Anchor component to add to points on any given page

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#715]
**As an editor I want a component that represent an anchor point that I can insert on any given page**

## TODO
- Define proper validation rules for the reference fields in Sanity
- Make it easy for the editors to understand if they are supposed to add the # or not in Sanity
- Find all occurrences of C2A both in Sanity and the web (query and components)
- The reference itself should only be added to the Text block and Accordion components

## Acceptance criteria

- A field for adding an anchor point is available in Sanity
- For CTA (links, buttons) it should be possible to reference an anchor point. We need to add a reference field where the editors type in the actual #reference.
- Need to be able to create URL containing the anchor link so stakeholders can send users directly to the point on the page  eg: https://www.equinor.com/en/investors.html#analytical-information
- Text block and accordion component: Anchor should be added to the containers for each of these components
- Validation rules in Sanity: The text fields where editors add the #reference must have validation rules to avoid mistakes like `#crude oil assets `instead of `#crude-oil-assets`

Connected to #346

**Comment by BirteThornquist** [comment]
For CTA (links, buttons) it should be possible to reference an anchor point. We need to add a reference field where the editors type in the actual #reference. 
something like:
![Skjermbilde 2022-01-13 kl. 15.44.26.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/bbbab0d6-7fd6-4da9-9bc5-54ded038f17c)

We have to decide where the anchors shall be placed. We have discussed adding them on header, H2 level. Another option could be to add the anchor on the component level (to the containers).  

![Skjermbilde 2022-01-13 kl. 15.50.41.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/03d109b5-d864-40a7-b5f8-8e5d9176a170)

**Comment by nicholas-haggerty** [comment]
@BirteThornquist One addition to this should be to also add anchor points to the ACCORIDON component. Some testing has been done below and its seems strange to add a Text component just for the title and then a separate component for the accordion. If we just use the Accordion we can add title/ingress and drop down description in one component and this also helps in the component overview for moving by having just one.![accordion.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/72f9d7e7-00ee-45c2-b38b-6dbebc8c4f54)

**Comment by BirteThornquist** [comment]
Absolutely @nicholas-haggerty, we should have anchor in the accordion component itself. I guess it will be use cases where you would want to anchor to a specific accordion item? Or just to the container? Should it be possible to add an anchor to the component title and also the items title? Is here any technical limitations to anchor to an accordion item @wenche?

![Skjermbilde 2022-01-24 kl  20 29 00](https://user-images.githubusercontent.com/74531659/150850942-ab537bfc-a8b9-490b-9db4-0e56ed5d8147.png)

**Comment by nicholas-haggerty** [comment]
@BirteThornquist Lets add to the component/container only.

**Comment by wenche** [comment]
@BirteThornquist @nicholas-haggerty  Is this ready to be finalised and moved into "Ready for implementation"? We should update the Acceptance criteria with the conclusions from the UX and discovery phase

**Comment by nicholas-haggerty** [comment]
@BirteThornquist I have updated with some comments, feel free to add more. I will move to Ready for Imp....

**Comment by BirteThornquist** [comment]
hi @nicholas-haggerty I can't find the comments... Did you comment in another issue or in Figma maybe?

**Comment by nicholas-haggerty** [comment]
Hey, to the acceptance criteria above

**Comment by BirteThornquist** [comment]
@nicholas-haggerty hmm - can't see them... Maybe you forgot to save...?

**Comment by nicholas-haggerty** [comment]
@BirteThornquist  nnnnnnnooooooowwwwwwww they are there :)

**Comment by wenche** [comment]
@nicholas-haggerty  Just to make it very clear in this issue itself: Internal links in rich text editors should **not** have the option to add a reference. This is just for standalone C2A buttons and links.

**Comment by SvSven** [comment]
Look into scroll-margin-top to offset menu

**Comment by SvSven** [comment]
There should be additional validation for adding an anchor to a component, the value added there should be unique for the document - having multiple elements with the same ID value is invalid HTML and can give unexpected results with linking to it

**Comment by SvSven** [comment]
A field for adding an anchor has been added to the Text block and Accordion component:

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/b69b88ef-d94c-4b9d-bcbf-d2598106e98b)

In addition a field has been added to the link selector component and the people promotion component in order to link directly to said anchors:

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/68015b7d-1372-4c1f-8d21-2b30ad1e1dc9)

The validation for these fields are as follows:
- Can only use letters, numbers, hyphens ( - ), and underscores ( _ )
- Can not use symbols, so adding the `#` symbol before it is **not** needed
- Adding an anchor to the component is optional, adding an anchor reference to a link is also optional
- The anchor you add to a component has to be unique for that page, meaning you cannot have several components with the same anchor **on the same page**.
- No white space is allowed, if the anchor consists of several words you should separate them with either hyphens and/or underscores.
  - Examples:
    This is invalid: `this is a test`
    This is valid: `this-is-a-test`
    This is also valid: `this_is_a_test`

There is currently not a limit where you can only add an anchor reference to an internal link. There is nothing stopping you from adding it for external or static links - we are assuming this should work out of the box but we have no control over external websites, and limited control over the static pages so this should be tested.

Creating a URL for linking to a section directly is as simple as just adding `#this-is-a-test` to the end of a URL where `this-is-a-test` is the value of the anchor you want to link to. This is just using the default browser behaviour, so as long as there is an element on the page that has an ID with that value, it should work.

**Comment by SvSven** [comment]
@BirteThornquist could you have a look at the Sanity part of this? You can test it in the Text Block component for adding an anchor, and for example the `Link/Action` on the Teaser component for linking to anchors.

**Comment by wenche** [comment]
LGTM Sven 👍

**Comment by SvSven** [comment]
@meols This should now be ready for review, see my comment above for details on how it's implemented.
It should be pretty solid so I'm reasonably optimistic 🤞

**Comment by nicholas-haggerty** [comment]
@SvSven @meols Looks good to go, nice work

**Comment by meols** [comment]
Great work @SvSven - thanks!
