### ISSUE TITLE
In order to improve the responsive layout for large screen sizes we need to make changes to the dynamic font-scale

### ISSUE THREAD

**Issue by vnys** [equinor/energyvision#717]
This is a placeholder issue, more information will be added. But in short: Now that we have some more content and we see what works and what doesn’t, there are certain improvements we need to make. One concern @wenche had for example, is if there are better methods than gradually increasing the font-size of the root-element. It’s also clear that the slope at which the font-size increases according to shouldn’t necessarily be the same for headings and body copy, but could perhaps be steeper for headings. Also, more than 70% of all visits are on full hd monitors and higher (1920x1080) – so these improvements will affect the majority of the visitors.  

I’ll work with @BirteThornquist on this issue in the coming week (week 2).

**Comment by nilsml** [comment]
Remember trunk-based development ;) @vnys

**Comment by vnys** [comment]
I know, old habbit ;)

**Comment by vnys** [comment]
I’ve used feature flags so I can just merge it in, it shouldn’t interefere with whatever else is going on at the moment.

**Comment by vnys** [comment]
I’ve made a [spreadsheet](https://docs.google.com/spreadsheets/d/1eUJSfEH3YsoCyui6u9xkYFf3GJbAB4hsR-OIIdOeu6k/edit?usp=sharing) with all the calculations, let me know if anyone wants an explanation of that – alternatively we can do that in one of the Monday meetings in the team. I’ve used the terms `mobile` to describe the viewport width of 375px and `desktop` to describe the 1920 width to keep it simple.

The typescale now looks like this: 

```css
--typeScale-00: clamp(calc(11.11 / 16 * 1rem), 0.12vw + 0.67rem, calc(12.94 / 16 * 1rem));
--typeScale-0 : clamp(calc(13.33 / 16 * 1rem), 0.25vw + 0.77rem, calc(17.25 / 16 * 1rem));
--typeScale-05: clamp(calc(14.61 / 16 * 1rem), 0.34vw + 0.83rem, calc(19.92 / 16 * 1rem));
--typeScale-1 : clamp(calc(16.00 / 16 * 1rem), 0.45vw + 0.89rem, calc(23.00 / 16 * 1rem));
--typeScale-2 : clamp(calc(19.20 / 16 * 1rem), 0.74vw + 1.03rem, calc(30.66 / 16 * 1rem));
--typeScale-3 : clamp(calc(23.04 / 16 * 1rem), 1.15vw + 1.17rem, calc(40.87 / 16 * 1rem));
--typeScale-4 : clamp(calc(27.65 / 16 * 1rem), 1.74vw + 1.32rem, calc(54.48 / 16 * 1rem));
--typeScale-5 : clamp(calc(33.18 / 16 * 1rem), 2.55vw + 1.48rem, calc(72.62 / 16 * 1rem));
```
So I’ve used the suggestion @wenche had about using calc to make the rem values more developer friendly. Not sure if there’s a notable performance penalty for that or not.  

This alternative is shorter, but perhaps more difficult to reason about: 

```css
--typeScale-00: clamp(0.69rem, 0.12vw + 0.67rem, 0.81rem));
--typeScale-0 : clamp(0.83rem, 0.25vw + 0.77rem, 1.08rem));
--typeScale-05: clamp(0.91rem, 0.34vw + 0.83rem, 1.25rem));
--typeScale-1 : clamp(1.00rem, 0.45vw + 0.89rem, 1.44rem));
--typeScale-2 : clamp(1.20rem, 0.74vw + 1.03rem, 1.92rem));
--typeScale-3 : clamp(1.44rem, 1.15vw + 1.17rem, 2.55rem));
--typeScale-4 : clamp(1.73rem, 1.74vw + 1.32rem, 3.41rem));
--typeScale-5 : clamp(2.07rem, 2.55vw + 1.48rem, 4.54rem));
```

I’ve kept two decimal places to make it easier to scan. In Figma, @BirteThornquist uses 1440 as a medium size in her design. I’ve added a column in the spreadsheet with the font-sizes at this breakpoint, but those values are not in code, because they’re a result of the intercept between the clamps. We could add those as comments after each line, but then again we might as well do that for all the values. So the first line in the second example could then be written as:

```css
--typeScale-00: clamp(0.69rem, 0.12vw + 0.67rem, 0.81rem)); // 375: 11.11px, 1440: 12.38px, 1920: 12.94px
```

Another thing that became apparent when working with this issue, is the naming. Having a typeScale from 1–5 (nobody uses 6 so I removed that), becomes an issue when a need arises to add more steps in between. Adding a step below `0` and calling that `small` breaks the naming convention, so I initially thought it would be better to call that `00`. But then @BirteThornquist and I discussed if there was a need for a step inbetween 0 and 1, and that’s more tricky. It could be called `0.5`, except that’s not a valid name in CSS, so I called it `05` for now. But I think we should discuss other options. One option could be to use a similar naming convention as the font-size keywords in css. Since `16px` is medium, the rest of the scale could look like this: 

```css
x-small
small
medium-small // half step
medium
large
x-large
xx-large
xxx-large
```

…or we could just keep the names as they are right now. It could also be that by compressing the mobile ratio to `1.125` (major second) the need for the extra steps disappear, but that remains to be tested. In any case, by using the spreadsheet to fine-tune the values it’s just a matter of copy and paste to change things later on now that the groundwork has been done.

**Comment by nicholas-haggerty** [comment]
@vnys @BirteThornquist @meols @nilsml Guess some elements from this work have been implemented now? Judging from the change in font sizes on the site. Some big issues as I see it with the changes. Desktop:  tiny titles on menu, HUGE titles on topics, footer issues.... The list goes on. Are we still in 'work in progress' on this, or was this the desired outcome? If its the latter, then I think more cherry picking work will be required improve the effect of this task.

**Comment by nicholas-haggerty** [comment]
@vnys ok good whew, work in progress still. I can stop being depressed. Guess Birte and I can go through once complete and make any adjustments needed.

**Comment by vnys** [comment]
One potential problem we have is that I was not able to build the Legacy CSS on my M1 Macbook or Codespaces with the current version of Sass – so even though it’s not first priority right now, it needs to be adressed at some point while we still have machines available that are supported the version of Sass that’s used in the legacy package.

**Comment by vnys** [comment]
> I can stop being depressed. 

Indeed 🤗

> Guess Birte and I can go through once complete and make any adjustments needed.

Yes, just invite me to the party as well if you want, it’s easier to tweak in the browser.

**Comment by vnys** [comment]
> One potential problem we have is that I was not able to build the Legacy CSS

Looks like it’s trivial to replace node-sass with dart-sass in the gulp script. Alternatively gulp could be replaced with npm scripts which requires a bit more work, but would result in a more modern and faster build setup. I think it would take a day at the most.

**Comment by SvSven** [comment]
> Looks like it’s trivial to replace node-sass with dart-sass in the gulp script. Alternatively gulp could be replaced with npm scripts which requires a bit more work, but would result in a more modern and faster build setup. I think it would take a day at the most.

I looked into this at some point a while ago to try and fix the problem with node-sass and python crashing the build process on Mac and Linux. I too thought that it should be trivial because dart-sass is now the primary compiler and should be a drop-in replacement for node-sass, but unfortunately that was not the case. I don't remember what all the problems were, but it ended up being a lot bigger than just replacing node-sass - which is why we ended up removing the legacy build script from the main build script and opted to just manually move the compiled & minified file into the web folder.

You're welcome to try it of course, maybe you will have better luck - but make sure you check with us first before integrating it into the main build/deploy process as we've been having a lot of issues with that already.

**Comment by vnys** [comment]
> make sure you check with us first before integrating it into the main build/deploy process

Duly noted 👍🏻

**Comment by BirteThornquist** [comment]
What's done:
Adjusted down the ratio number for the scale to 1.25 from 1.33. The base text is still 20 for medium size screens (1440) and the max paragraph text size is adjusted down to 22px from previous 23px. Smaller paragraph text is kept at 16px. This means the H2 text is 4px smaller than before and also the ingress text is smaller. We also added a step (scale6) in order to get a bit bigger and slimmer H1, and the difference between H1 and H2 is now bigger.

For H3 the editors wanted to have the same size as the paragraph text, but bold. Today they often use bold text for H3 to get this style. So we adjusted down H3 style in size to the same as the paragraph text size, but increased the font weight to 450 (medium). We also increased spacing below to the paragraph text. 

We set the footer text up to half a step -05 (gives the size 18.11 for meduim size viewport, 1440)
Set button text  one step up to typescale - 05 (18.11 on 1440 screen size) It was 16 px and felt too small.

Menu bug is fixed, no other changes.

Nick: we can take a walkthrough when we are in Oslo to check  and see if we want to adjust something. Adjustments should be quick and easy going forward, and the responsive scaling should work smoothly.
