### ISSUE TITLE
Icon files downloaded as jpgs

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#739]

**Comment by nicholas-haggerty** [comment]
Downloaded an icon from brandmaster, which should be an SVG, is pulled into MEDIA as a jpg and displays with a white background. Can be seen here:

https://equinor.sanity.studio/desk/topicContent;1b08e4d3-17a7-46d2-bba9-f16de70579d2

**Comment by nilsml** [comment]
Probably connected to #740

**Comment by SvSven** [comment]
Can confirm I am getting the same result with that "equinor-data" icon when I import it from Brandmaster.
Doesn't seem to be happening with every SVG icon that I try though - which indicates it might be a problem with that icon in particular.

**Comment by SvSven** [comment]
@nicholas-haggerty I don't seem to have access to the media bank for icons and illustrations when accessing Brandmaster via https://communicationtoolbox.equinor.com - while I do have access via the plugin? Very strange.

Can you double check inside Brandmaster itself whether that particular icon is indeed an SVG? Because my suspicion is that there is an imposter among us... 🕵️‍♀️

**Comment by SvSven** [comment]
Managed to find out how to access the icons and illustrations. I think the web plugin for this integration is a bit more intuitive for navigation really 😅
Turns out I was _partially_ correct! It is indeed an SVG in Brandmaster, but there is something off with the file in Brandmaster; the order of the list with different versions for this file is not what was expected, so it was selecting a cached jpg version instead of the original or the "for equinor.com" version.

Have fixed it now to be more explicit and robust in which version it selects, should now ignore the different versions and always select the original regardless.

**Comment by SvSven** [comment]
@nicholas-haggerty @meols you will unfortunately have to replace this image wherever it is used in Sanity and re-select it from Brandmaster. With the way Sanity handles assets we can't just replace the file in the media library to fix it, so it's a good thing this got noticed now and not weeks/months later.

Luckily you can see all the pages where an asset is used in the media plugin by opening the asset and clicking the "References" button

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/e3d32fdb-5ab0-458f-8140-69204b94b266)

**Comment by nicholas-haggerty** [comment]
@SvSven Hey thanks for looking into this. Still seems to be a problem with that particular icon/file. I deleted it in media and re added to the teaser and it still cam as a jpg. I tried a few example and they come in as SVGs.

**Comment by nicholas-haggerty** [comment]
@SvSven  I think we can just assume its a rogue file. I will find the original and upload it. In terms of the card. The svg displays now and works with both the smaller and full display. I will close this and the related card.

**Comment by SvSven** [comment]
That's strange, it worked for me locally. It might be that the changes I made did not get deployed to the studio yet, as we were having some issues with automatic deployment with regards to the satellite studios - I'll have a look into it
