### ISSUE TITLE
Update warning on news preview for articles without a slug

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#755]
![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/059e82ef-86df-4f8f-a521-86b143e3a2ff)

A news article is not a product.

This should be updated to something along the lines of `A slug is required in order to preview this news article`.  
Should also add some margin/padding around the message to make it look a bit better.

Related to #652

**Comment by SvSven** [comment]
Potentially we can also implement preview by ID here like we do with the topic content? Should still update the warning, but then we no longer need a slug 👍

**Comment by wenche** [comment]
Nice suggestion about the preview by ID instead. It could be worth to look into :thumbsup: I don't want to mess up more here now since we already have issues with news preview (#1159), but def. something to take into consideration. 

I'll create a new issue for your suggestion.

I have updated the preview message
![Skjermbilde 2022-06-16 kl. 14.43.48.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/ad05953e-40e5-40cc-b35d-5b7344a267a0)

**Comment by wenche** [comment]
@SvSven  What do you think? Added #1161 for the id suggestion

**Comment by SvSven** [comment]
Perfect 👍
