### ISSUE TITLE
PDF files not opening in mobile view

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#763]
PDF preview happens in desktop screen but not in smaller devices. Update: PDF downloads in mobiles

Note : In current production, all the PDFs are downloaded by default. The pdfs in static pages are downloaded.

**Comment by SvSven** [comment]
Is this when clicking on a PDF link in the web? Because I think that's the default browser/operating system behavior; on desktop/Windows it tends to open a PDF viewer in the browser, whereas on mobile it downloads the file and in some cases prompts the user to ask which app to use to view the file. Not sure if that's something we can control.

**Comment by fernandolucchesi** [comment]
This is a behaviour of the browsers.
