### ISSUE TITLE
Add logo to menu in both global and simple site

### ISSUE THREAD

**Issue by adneforslund** [equinor/energyvision#774]
Add logo to menu in both global and simple site

**Comment by wenche** [comment]
@adneforslund  What about you question in the commit, was the answer yes?
 ![Skjermbilde 2022-01-20 kl. 09.30.18.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/54530966-bb26-4fa5-83a3-3b878b429897)

**Comment by wenche** [comment]
@adneforslund  I think this code is not perfect, it's somewhat messy but that's not your fault @adneforslund since a lot of people have been involved including myself :sweat_smile:

I still think we should create a component of the StyledLogoLink instead of code duplication x 3. What do you think? It's also hard to see where the actual grid is since it's just the grid-area in the menus. Can we be more explicit here and use 
```
${TopbarContainer} & {
grid-area: logo;
}
```
instead to make it easer to understand and slightly less error prone further down the road (inside the new component)

**Comment by adneforslund** [comment]
@wenche yes, it should be visible

**Comment by wenche** [comment]
@adneforslund  I tried to refactor this code slightly - kill me if you disagree, close this issue it you agree
