### ISSUE TITLE
Create pagination or load more component

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#829]
If a query has more than a predefined hits (the hits per page limit), it should be able to load more results.

https://www.algolia.com/doc/api-reference/widgets/pagination/react-hooks/

## Discussions
- What should the hits per page limit be
- Load more button vs pagination (design has load more atm)
- Nail the design

## Acceptance criteria
- Pagination works as expected with regards to number of search results (5 results per page)
- The pagination is easy and intuitive to use, and needs to be accessible
- Pagination is implemented according to design
- Pagination should work both on desktop and mobile devices
- Pagination should have the following controls: First page, Previous Page, Next page, Last page
- Pagination should be hidden if there are only 5 or less search results

**Comment by SvSven** [comment]
On hold pending UX feedback

**Comment by wenche** [comment]
Note to future @SvSven  The pagination component doesn't update itself correctly on state change. When you type for example "Equin" and select page 5 and then type more like "Equinor" the pagination component still has 5 as the active page even if the result list is back to the first page. (Showing 1-5 of the results)

Will probably need to be looked at together with the url state in general but the default for the original version of the library is to reset the page to 1 if the search changes/updates https://www.algolia.com/doc/guides/building-search-ui/widgets/showcase/react/ I think we will make it hard for ourselves if we change this.

**Comment by BirteThornquist** [comment]
@SvSven I have updated the design of pagination in Figma [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4566%3A82832) It is still the EDs look and feel, but I have made the clickbound 44px instead of 48px and altered the colors a bit. For mobile we could also place the arrow on a line above the page numbers. Lets look into and discuss when you are back and ready to pick this up again.

**Comment by SvSven** [comment]
Due to a technical limitation in the way Algolia uses pagination, we can't quite get it to look like we have in the design with the ellipsis. The way it works is that you configure how many "siblings" the currently active page should have, and then it will generate the list of page numbers automatically.

This means that if, for example, you say there should always be 1 page next to the currently active on, it would look something like this:

`< 3 4 5 >`

To work around this, I added a "First page" and a "Last page" button so that the user can instantly go to the first/last page. See screenshot:

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/477aa9f0-4b00-4ba8-afa6-d24d109d6ff8)

I don't think this is the _ideal_ way of doing pagination, and maybe we can get it to work the way we want with enough time - but not sure if its worth spending more time on right now.

**Comment by SvSven** [comment]
@BirteThornquist this is ready to be looked at again

**Comment by BirteThornquist** [comment]
hi @SvSven It does not seem like the disabled color has changed? Have you set it to slate blue 90? ![Skjermbilde 2022-03-04 kl. 12.49.39.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/c762f888-486e-466d-acea-b1f94423a03d)

**Comment by SvSven** [comment]
Yes... pushing the commit that changed that would be smart. I blame all the meetings.
It should be updated now.

**Comment by BirteThornquist** [comment]
😄

**Comment by wenche** [comment]
Hide it on less than 5 hits as well :thumbsup:

**Comment by SvSven** [comment]
Fixed 👍

**Comment by SvSven** [comment]
@meols This is ready for review. We don't currently store the pagination in the URL yet, but we have made an issue to do this #915

**Comment by meols** [comment]
@wenche - great if you can add some acceptance criteria for me to test.
@SvSven

**Comment by SvSven** [comment]
@meols I have updated the acceptance criteria list

**Comment by wenche** [comment]
@meols

**Comment by meols** [comment]
@SvSven @wenche - looks good and work as it should :smile:
One question:
On mobile the logo is "marked/framed" when I open the search page. Is that noted and will be fixed?
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/637d04a5-6341-496e-804a-987e36f6d434)

**Comment by wenche** [comment]
@meols  This is iPhone right? We've seen this for some of the menu links as well, it's not like this on my Android phone. The way focus work is slightly different between the two platforms. This one in particular is not covered by an issue, you may create an issue for it in the backlog.

**Comment by meols** [comment]
@wenche - yes it's iPhone.
I have created #935 and close this one. Thanks
