### ISSUE TITLE
Fix error message regarding "content"

### ISSUE THREAD

**Issue by adneforslund** [equinor/energyvision#905]
![Screenshot 2022-03-08 at 15.23.42.png](https://images.zenhubusercontent.com/61482e3b2cb1bada8cadcc42/68de0358-6c34-4fe5-82c9-635abd1dd9d4)

**Comment by adneforslund** [comment]
Only on global datset for at the moment

**Comment by SvSven** [comment]
Looks to have been fixed by f3fefd112dbc59cda3dee04c7601420f738aed12 and 9905b2ad26a2bdb0e96e3563371d68c37f5e2e99

Those commits were meant to fix a seemingly unrelated error, namely this one: https://nextjs.org/docs/messages/next-head-count-missing

Why this only happened on the global dataset, and why the error was different on localhost, is beyond me - but at least it seems to be fixed now.
