### ISSUE TITLE
Cookie pop up message

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#916]

**Comment by meols** [comment]
@nilsml - we have noticed that the cookie popup doesn't indicate which cookie a user needs to accept to e.g. see an embedded YouTube video (marketing cookie), or a Vimeo streaming (statistics cookie). Users should be informed and able to choose only the applicable cookie.
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/26988dcb-d890-43bd-8431-d4bd29780ccd)

**Comment by nilsml** [comment]
Is this handled differently in this solution compared to AEM @meols @padms ?

**Comment by nilsml** [comment]
Apparently this was removed from the new design when Nick and @BirteThornquist was working with it. Is there any legal reason why we should bring it back @meols?

**Comment by wenche** [comment]
The type of cookie is now added. 5 corresponding text snippets are added in Sanity. 
![Skjermbilde 2022-04-05 kl. 20.32.56.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/e770ddfd-532f-4f1d-925c-b9498d9c5865)
The type of cookie is added in the fields `Cookie: Type marketing` and `Cookie: Type statistics` and in interpolated into the message by the id {typeOfCookie}.  The full example text for Cookie: Information text will then be 
`Want the full picture? We’d love to share this content with you, but first you must accept {typeOfCookie} cookies by enabling them in our cookie settings.`

The end result will be like this (example from [my test page in the dev environment](https://web-global-development-energyvision-dev.radix.equinor.com/test/wenches))
![Skjermbilde 2022-04-05 kl. 20.16.54.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/fd9c7a1d-1e3f-461e-a884-b9f71d5547e5)
![Skjermbilde 2022-04-05 kl. 20.16.58.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/77aac1ff-ebee-46dc-8388-7f020bb840a2)
![Skjermbilde 2022-04-05 kl. 20.20.27.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/b028cf0b-0601-424c-97fa-450837f83559)
![Skjermbilde 2022-04-05 kl. 20.20.32.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/c0a849bf-9e80-4817-aacd-ba16cbb915f1)

I have also added some CSS for unbreakable boxes since some  words might be pretty long in certain languages, so it should handle this.
![Skjermbilde 2022-04-05 kl. 20.20.13.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/52932384-b079-4f3b-b04d-c456c807a586)

**Comment by wenche** [comment]
@meols This is fixed now, and you'll need to update the [text snippets for storage](https://studio-storage-energyvision-prod.radix.equinor.com/desk/settings;textSnippets;snippet-cookie_consent) :)

**Comment by meols** [comment]
Thanks @wenche - and the text snippets for Storage are updated
