### ISSUE TITLE
Create Careers Contact Form

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#938]
## Acceptance criteria
- Be able to add 'Order reports' in topic page, with title and ingress ( optional) 
- Be able to add or modify the translations for the form  field labels, text  and error messages.
- Be able to successfully submit the form and verify that RITM is created in service now ( https://equinortest.service-now.com/nav_to.do?uri=%2Ftask_list.do%3Fsysparm_query%3Dcmdb_ci%253D59e02ac8375a3640615af01643990e7c%26sysparm_first_row%3D1%26sysparm_view%3D )
- Validations are done properly.

**Comment by padms** [comment]
@BirteThornquist @meols For your review.

**Comment by meols** [comment]
@padms @BirteThornquist - some comments:
- Translations are working
- When selecting Event. "Would like to visit Equinor office or facility" is chosen, the text "Please be aware that we only offer visits to a few selected locations. Please specify your preferred location and we will revert to you as soon as we can." should show up ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/ad7bc90f-8aba-485b-a80e-405d4b85c359)
- I am not able to confirm if my info is received in serviceNow - maybe because I don't have access to the assignment groups? I saw three RITMs created by me, but have submitted more (tested at all forms and some alternatives). Can you check @padms ?
(and the same general form comments on recaptcha, validation text size, recaptcha)

**Comment by padms** [comment]
@meols I cannot find the tickets you created in stage ( May be service now synced their prod data to stage ). Let me know when you are testing, I can verify the ticket immediately.

**Comment by meols** [comment]
@padms - I submitted a form just now (09:53), but got an error message ("Sorry, something went wrong")

**Comment by padms** [comment]
@meols I found the ticket in service now

**Comment by meols** [comment]
Thanks @padms
