### ISSUE TITLE
Go to a separate URL for the main site search

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#945]
This is to avoid several bugs we see if somebody opens the main site search while on`/news` and also to make it easier in the long run.

Take a look at how the site search works on the Algolia page itself. :) 

### Acceptance criteria
- When a user clicks on the search icon, they will be sent to `/search` TODO: Figure out if we need another URL for Norwegian or not
- When the user clicks on the "Close search" icon, they will be sent to the page from where they opened the search overlay  (Next router history back)

**Comment by wenche** [comment]
One strange behaviour with the Algolia page:

1.  Navigate to a sub page (https://www.algolia.com/distributed-secure/security-compliance/)
2. Open the search -> Sent to `/search`
3. Search for something like "test"
4. Go to a hit from the hit list, like "https://www.algolia.com/products/search-and-discovery/ab-testing/"
5. Browser back -> sent back to the full restored search page
6. Click on the "Close search" icon. -> BOOM, stuck on /search and I need to manipulate the URL to close the search

We need to improve this!

**Comment by SvSven** [comment]
This should now be working, with a hard-coded link on the search icon to `/search`
I think we can live with the URL being `/search` for both English and Norwegian, but if we want we can create a dedicated Norwegian path as well.

Additionally I have updated the query params in search to use `router.replace` instead of `router.push` in order to not pollute the browser history too much so we can get the "back" behaviour we want.

**Comment by wenche** [comment]
This seems to be working as expected :)

Tested with
1. Open the search overlay
2. Search for something
3. Go to a hit
4. Go back using browser back
5. Close the search
6. End result: start page

1. Open the search
2. Search for something
3. Go to a hit
4. Open the search overlay again
5. Close
