### ISSUE TITLE
Switch Sanity to private datasets

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#974]
In order to switch from public to private dataset, we need to make sure we are filtering out all the draft contents in the web, but keeping them during preview. 

There are exceptions such as the "latestNews" and the "latestPromotions" components. In these cases, drafts should be filtered out for both preview and web.

## Test example
1. Create a news article
1. Add the mandatory content
1. Publish the news article
1. Change some of the content -> draft content + published content
Expected result: 
-Preview inside Sanity studio -> can see the draft changes
- The url in the same browser as the logged in session in Sanity -> can see the draft changes
- Another browser or incognito mode -> can only see the published content

**Comment by fernandolucchesi** [comment]
@wenche @SvSven could you both please take a look at this? This is quite a critical change 😬

**Comment by wenche** [comment]
I'm not able to find any big issues with this, which is good :thumbsup: Tried to play around with the api directly, tested some content in Sanity/web and read through the queries.

The filter to one document is a critical component here and important to not screw up :) It's also crucial to run this logic server side. 

(A little bit confusing that the preview of content in the web for news and for topics work different because of the route logic, but it's unrelated to this change)

**Comment by SvSven** [comment]
Have not come across any issues so far, so I think we're good with this?
