### ISSUE TITLE
Hits in the search list show the url for the search page

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#981]

**Comment by meols** [comment]
When searching, the results in the search result list all show the url for the search page, instead of "their own" url
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/95a40a13-b4a9-4fe7-9d21-22ffb21c5b5a)

**Comment by wenche** [comment]
This was due to the logic for getting the full url. 

To avoid unnecessary complexity, the visible text will be the production domain even if we are not in production yet (https://www.equinor.com/the-slug instead of https://web-energyvision-prod.radix.equinor.com/the-slug) but the url itself will be correct.

**Comment by wenche** [comment]
@SvSven  to verify

**Comment by SvSven** [comment]
Can confirm that the URLs listed in the hits are showing correctly again 👍
